#!/usr/bin/env python
# -*- coding: utf-8 -*-

language_specific_alt_form_of_templates = [
  u"be-Taraškievica",
  "bg-pre-reform",
  "ceb-superseded spelling of",
  "egy-alternative transliteration of", "egy-alt",
  "en-ing form of",
  "fr-post-1990",
  "fr-pre-1990",
  "hy-reformed",
  "jbo-rafsi of", "rafsi of",
  "morse code abbreviation",
  "morse code for",
  "morse code prosign",
  "my-ICT of",
  "pt-superseded-paroxytone",
  "ru-pre-reform",
  "uk-pre-reform",
  "yi-alternatively pointed form of",
  "yi-phonetic spelling of",
  "yi-unpointed form of",
]

alt_form_of_templates = [
  "abbreviation of", "abbr of",
  "acronym of",
  "archaic form of",
  "archaic spelling of",
  "aspirate mutation of",
  "clipping of", "clip of",
  "contraction of",
  "dated form of",
  "dated spelling of",
  "deliberate misspelling of",
  "eclipsis of",
  "eggcorn of",
  "elongated form of",
  "euphemistic form of",
  "euphemistic spelling of",
  "eye dialect of",
  "former name of",
  "hard mutation of",
  "informal form of",
  "informal spelling of",
  "initialism of", "init of",
  "lenition of",
  "misromanization of",
  "misspelling of", "missp",
  "mixed mutation of",
  "nasal mutation of",
  "nomen sacrum form of",
  "nonstandard form of",
  "nonstandard spelling of",
  "obsolete form of",
  "official form of",
  "pronunciation spelling of",
  "pronunciation variant of",
  "rare form of",
  "rare spelling of", "rare sp",
  "short for",
  "soft mutation of",
  "standard form of",
  "standard spelling of", "stand sp",
  "superseded spelling of",
  "uncommon form of",
  "uncommon spelling of",
]

language_specific_form_of_templates = [
  "ar-verbal noun of",
  "bg-adjective extended of",
  "bg-adjective feminine definite of",
  "bg-adjective feminine indefinite of",
  "bg-adjective masculine definite object of",
  "bg-adjective masculine definite subject of",
  "bg-adjective neuter definite of",
  "bg-adjective neuter indefinite of",
  "bg-adjective plural definite of",
  "bg-adjective plural indefinite of",
  "bg-plural count of",
  "bg-singular definite object form of",
  "bg-singular definite subject form of",
  "blk-past of",
  "cs-imperfective form of",
  "cu-Glag spelling of",
  "da-e-form of",
  "da-pl-genitive",
  "de-du contraction",
  "de-inflected form of",
  "egy-verb form of",
  "el-form-of-verb", "el-verb form of",
  "el-monotonic form of",
  "el-polytonic form of",
  "en-archaic second-person singular of",
  "en-comparative of",
  "en-irregular plural of",
  "en-past of",
  "en-simple past of",
  "en-superlative of",
  "ga-emphatic of",
  "ga-lenition of",
  "hu-exaggerated of",
  "hy-traditional",
  "ia-form of",
  "ie-past and pp of",
  "ja-kyujitai spelling of", "ja-kyu sp",
  "ja-new/r", "jaro",
  "ja-past of verb",
  "ja-romanization of", "ja-romanization-of",
  "ja-te form of verb",
  "ja-verb form of",
  "lb-inflected form of",
  "mn-verb form of",
  "pt-cardinal form of",
  "pt-pronoun-with-l",
  "pt-pronoun-with-n",
  "ro-adj-form of", "ro-form-adj",
  u"ru-alt-ё",
  "ru-abbrev of",
  "ru-acronym of",
  "ru-clipping of",
  "ru-initialism of",
  "ru-participle of",
  "sa-desiderative of", "desiderative of", "sa-desi",
  "sa-frequentative of", "sa-inten", "sa-freq",
  "sa-root form of",
  "sce-verb form of",
  "sco-past of",
  "sco-simple past of",
  "sga-verbnec of",
  "sino-vietnamese reading of",
  "ug-uly of",
  "ug-uyy of",
  "yi-inflected form of",
  "za-sawndip form of",
]

form_of_templates = [
  "abstract noun of",
  "accusative of",
  "accusative plural of",
  "accusative singular of",
  "active participle of",
  "agent noun of",
  "alternative case form of", "alt case",
  "alternative form of", "alt form", "altform", # "alt form of" (deprecated)
  "alternative plural of",
  "alternative reconstruction of",
  "alternative spelling of", "alt sp",
  "alternative typography of",
  "aphetic form of",
  "apocopic form of",
  "attributive form of",
  "augmentative of",
  "broad form of",
  "causative of",
  "combining form of",
  "comparative of",
  "construed with",
  "dative of",
  "dative plural of",
  "dative singular of",
  "definite of",
  "diminutive of", "dim of",
  "diminutive plural of",
  "dual of",
  "elative of",
  "ellipsis of",
  "equative of",
  "feminine noun of",
  "feminine of",
  "feminine plural of",
  "feminine plural past participle of",
  "feminine singular of",
  "feminine singular past participle of",
  "form of",
  "frequentative of",
  "future participle of",
  "genitive of",
  "genitive plural definite of",
  "genitive plural indefinite of",
  "genitive plural of",
  "genitive singular definite of",
  "genitive singular indefinite of",
  "genitive singular of",
  "gerund of",
  "h-prothesis of",
  "harmonic variant of",
  "honorific alternative case form of", "honor alt case",
  "imperative of",
  "imperfective form of",
  "inflected form of",
  "inflection of", # "conjugation of" (deprecated)
  "iterative of",
  "masculine noun of",
  "masculine of",
  "masculine plural of",
  "masculine plural past participle of",
  "medieval spelling of",
  "men's speech form of",
  "misconstruction of",
  "negative of",
  "neuter plural of",
  "neuter singular of",
  "neuter singular past participle of",
  "nominalization of",
  "nominative plural of",
  "nominative singular of",
  "nuqtaless form of",
  "obsolete spelling of", "obs sp",
  "obsolete typography of",
  "participle of",
  "passive of",
  "passive participle of",
  "passive past tense of",
  "past active participle of",
  "past participle form of",
  "past participle of",
  "past passive participle of",
  "past tense of",
  "pejorative of",
  "perfect participle of",
  "perfective form of",
  "plural definite of",
  "plural indefinite of",
  "plural of", # "plural form of" (deprecated)
  "present active participle of",
  "present participle of",
  "present tense of",
  "reflexive of",
  "rfform",
  "second-person singular past of",
  "singular definite of",
  "singular of",
  "singulative of",
  "slender form of",
  "spelling of",
  "superlative attributive of",
  "superlative of",
  "superlative predicative of",
  "supine of",
  "syncopic form of",
  "synonym of", "syn of",
  "t-prothesis of",
  "verbal noun of",
  "vocative plural of",
  "vocative singular of",
]

manual_templates = [
  "ja-form of",
  "jyutping reading of",
]
