local tests = require('Module:UnitTests')
local m_ru_pron = require('Module:ru-pron')
local m_links = require('Module:links')

local lang = require('Module:languages').getByCode('ru')

function tests:check_pron(Cyrl, IPA, Cyrl_word, gem)
	self:equals(
		m_links.full_link(Cyrl_word or Cyrl, Cyrl_word or Cyrl, lang, nil, nil, nil, { tr = '-' }, true) ..
			(Cyrl_word and (" (respelled " .. Cyrl .. ")") or "") .. (gem and ", gem=" .. gem or ""),
		m_ru_pron.ipa(Cyrl, nil, gem),
		IPA,
		{nowiki=true}
	)
end

function tests:test_pron()
	self:check_pron("а не то", "ɐ‿nʲɪ‿ˈto")
	self:check_pron("а как же", "ɐ‿ˈkag‿ʐɨ")
	self:check_pron("а̂ капэ́лла", "a kɐˈpɛl(ː)ə", "а капе́лла", "opt")
	self:check_pron("о-а-э́", "o a ˈɛ")
	self:check_pron("лёгкий", "ˈlʲɵxʲkʲɪj")
	self:check_pron("мя́гкий", "ˈmʲæxʲkʲɪj")
	self:check_pron("не́‿за‿што", "ˈnʲe‿zə‿ʂtə", "не́ за что")
	self:check_pron("град идёт", "ɡrat ɪˈdʲɵt")
	self:check_pron("гра̂д‿идёт", "ɡrad‿ɨˈdʲɵt", "град идёт")
	self:check_pron("град‿идёт", "ɡrəd‿ɨˈdʲɵt", "град идёт")
	self:check_pron("ро́г‿изоби́лия", "ˈroɡ‿ɨzɐˈbʲilʲɪjə", "ро́г изоби́лия")
	self:check_pron("приводи́ть в замеша́тельство", "prʲɪvɐˈdʲidʲ v‿zəmʲɪˈʂatʲɪlʲstvə")
	self:check_pron("ты ве́ришь в Бо́га", "tɨ ˈvʲerʲɪʐ ˈv‿boɡə")
	self:check_pron("муж Ва́ли", "muʂ ˈvalʲɪ")
	self:check_pron("брат вдовы́", "brad vdɐˈvɨ")
	self:check_pron("ваш взор", "vaʐ vzor")
	self:check_pron("от взгля́дов", "ɐd‿ˈvzɡlʲadəf")
	self:check_pron("каки́е-нибудь лека́рства", "kɐˈkʲi(j)ɪ‿nʲɪbʊtʲ lʲɪˈkarstvə")
	self:check_pron("волк ка́ждый год линя́ет", "volk ˈkaʐdɨj ɡot lʲɪˈnʲaɪt, volk ˈkaʐdɨj ɡot lʲɪˈnʲæjɪt")
	self:check_pron("код Мо́рзэ", "kot ˈmorzɨ", "код Мо́рзе")
	self:check_pron("наря́д на ку́хню", "nɐˈrʲat nɐ‿ˈkuxnʲʊ")
	self:check_pron("ждать щу́ку", "ʐdat͡ɕ ˈɕːukʊ")
	self:check_pron("за́пись Шу́берта", "ˈzapʲɪɕ ˈʂubʲɪrtə")
	self:check_pron("гусь жа́ренный", "ɡuʑ ˈʐarʲɪn(ː)ɨj")
	self:check_pron("туз черве́й", "tuɕ t͡ɕɪrˈvʲej")
	self:check_pron("о̀ргкомите́т", "ˌorkːəmʲɪˈtʲet")
	self:check_pron("То́кио же", "ˈtokʲɪo‿ʐɨ")
	self:check_pron("ве́псский", "ˈvʲepsːkʲɪj")
	self:check_pron("Черке́сск", "t͡ɕɪrˈkʲesːk")
	self:check_pron("ада́жио", "ɐˈdaʐɨo")
	self:check_pron("арпе́джио", "ɐrˈpʲed͡ʐʐɨo")
	self:check_pron("с глаз доло́й — из се́рдца вон", "ˈz‿ɡlaz dɐˈloj | ɪs‿ˈsʲert͡sə von")
	self:check_pron("аппле́т", "ɐˈplʲet")
	self:check_pron("Киргизста́н", "kʲɪrɡʲɪˈstan")
	self:check_pron("жжёт", "ˈʐːot")
	self:check_pron("друг к дру́гу", "druɡ ˈɡ‿druɡʊ")
	self:check_pron("(и) пода́вно", "(i) pɐˈdavnə")
	self:check_pron("рабфа́к", "rɐpˈfak")
	self:check_pron("со́бственник", "ˈsopstvʲɪnʲ(ː)ɪk")
	self:check_pron("твё́рдость", "ˈtvʲɵrdəsʲtʲ")
	self:check_pron("просчё́т", "prɐˈɕːɵt")
	self:check_pron("кало́сс", "kɐˈlos")
	self:check_pron("Иоа́нн", "ɪɐˈan")
	self:check_pron("йе́ти", "ˈjetʲɪ")
	self:check_pron("а̀нгло-норма́ннский", "ˌanɡlə nɐrˈmanskʲɪj")
	self:check_pron("фуррь", "furʲ")
	self:check_pron("ха́о̂с", "ˈxaos", "ха́ос")
	self:check_pron("эвфеми́зм", "ɨfʲɪˈmʲizm")
	self:check_pron("хору́гвь", "xɐˈrukfʲ")
	self:check_pron("ко̀е-кто́", "ˌko(j)ɪ ˈkto")
	self:check_pron("по абази́ну", "pɐ‿ɐbɐˈzʲinʊ")
	self:check_pron("под абази́ном", "pəd‿əbɐˈzʲinəm")
	self:check_pron("подсти́лка", "pɐtʲ͡sʲˈsʲtʲilkə")
	self:check_pron("э́ллипс", "ˈɛlʲɪps")
	self:check_pron("иди́ллия", "ɪˈdʲilʲɪjə")
	self:check_pron("-ин", "ɪn")
	self:check_pron("собра́ние", "sɐˈbranʲɪ(j)ə")
	self:check_pron("фойе́", "fɐˈjːe", nil, "y")
	self:check_pron("льстец", "lʲsʲtʲet͡s")
	self:check_pron("инсти́нкт", "ɪn⁽ʲ⁾ˈsʲtʲinkt")
	self:check_pron("ни́ндзя", "ˈnʲinʲdʲ͡zʲzʲə")
	self:check_pron("Хэйлунцзя́н", "xɨjlʊnʲdʲ͡zʲˈzʲan")
	self:check_pron("проце́нтщик", "prɐˈt͡sɛnʲɕːɪk")
	self:check_pron("брюзжа́ть", "brʲʊˈʐːatʲ")
	self:check_pron("львёнок", "ˈlʲvʲɵnək")
	self:check_pron("помпе́зный", "pɐm⁽ʲ⁾ˈpʲeznɨj")
	self:check_pron("любви́", "lʲʊbˈvʲi, lʲʉbʲˈvʲi")
	self:check_pron("обвини́тельный", "ɐbvʲɪˈnʲitʲɪlʲnɨj")
	self:check_pron("вбира́ть", "v⁽ʲ⁾bʲɪˈratʲ")
	self:check_pron("впечатли́тельный", "f⁽ʲ⁾pʲɪt͡ɕɪˈtlʲitʲɪlʲnɨj")
	self:check_pron("дѐло в то́м, што", "ˌdʲelə ˈf‿tom | ʂto", "де́ло в то́м, что")
	self:check_pron("де́вственная плева́", "ˈdʲefstvʲɪn(ː)əjə plʲɪˈva")
	self:check_pron("хуаця́о", "xʊɐˈtʲ͡sʲao")
	self:check_pron("Цю́рих", "ˈtʲ͡sʲʉrʲɪx")
	self:check_pron("тайцзицюа́нь", "təjdʲ͡zʲzʲɪtʲ͡sʲʊˈanʲ")
	self:check_pron("Цзили́нь", "dʲ͡zʲzʲɪˈlʲinʲ")
	self:check_pron("будь што бу́дет", "but͡ɕ ʂto ˈbudʲɪt", "будь что бу́дет")
	self:check_pron("дух бодр, плоть же не́мощна", "duɣ bodr | ˈplod͡ʑ‿ʐɨ ˈnʲeməɕːnə")
	self:check_pron("Пи́тсбург", "ˈpʲid͡zbʊrk")
	self:check_pron("Ло̀с-А́нджелес", "ˌlos ˈand͡ʐʐɨlʲɪs")
	self:check_pron("АльДжази́ра", "ɐlʲd͡ʐʐɐˈzʲirə", "Аль-Джази́ра")
	self:check_pron("всле́дствие", "ˈfs⁽ʲ⁾lʲet͡stvʲɪjə")
	self:check_pron("Петрозаво́дск", "pʲɪtrəzɐˈvot͡sk")
	self:check_pron("Джо́рджтаун", "ˈd͡ʐʐort͡ʂʂtəʊn")
	self:check_pron("Нджаме́на", "nd͡ʐʐɐˈmʲenə")
	self:check_pron("муншту́к", "mʊnʂˈtuk", "мундшту́к")
	self:check_pron("Джордж", "d͡ʐʐort͡ʂʂ")
	self:check_pron("Гуйчжо́у", "ɡʊjˈd͡ʐʐoʊ")
	self:check_pron("Чжэцзя́н", "d͡ʐʐɨˈdʲ͡zʲzʲan")
	self:check_pron("аге́нтство", "ɐˈɡʲent͡stvə")
	self:check_pron("с жено́й", "ʐ‿ʐɨˈnoj")
	self:check_pron("без ша́пки", "bʲɪʂ‿ˈʂapkʲɪ")
	self:check_pron("отста́вка", "ɐt͡sˈstafkə")
	self:check_pron("отстегну́ть", "ɐtʲ͡sʲsʲtʲɪɡˈnutʲ")
	self:check_pron("подсласти́тель", "pət͡sslɐˈsʲtʲitʲɪlʲ")
	self:check_pron("о́тзвук", "ˈod͡zzvʊk")
	self:check_pron("коттэ́дж", "kɐˈtɛt͡ʂʂ", "котте́дж")
	self:check_pron("подсчёт", "pɐt͡ɕˈɕːɵt")
	self:check_pron("отсчи́тываться", "ɐt͡ɕˈɕːitɨvət͡sə")
	self:check_pron("отжи́ть", "ɐd͡ʐˈʐɨtʲ")
	self:check_pron("таджи́к", "tɐd͡ʐˈʐɨk")
	self:check_pron("дщерь", "t͡ɕɕːerʲ")
	self:check_pron("тще́тно", "ˈt͡ɕɕːetnə")
	self:check_pron("мла́дший", "ˈmlat͡ʂʂɨj")
	self:check_pron("отшиби́ть", "ɐt͡ʂʂɨˈbʲitʲ")
	self:check_pron("пядь земли́", "pʲædʲ͡zʲ zʲɪˈmlʲi")
	self:check_pron("под сту́лом", "pɐt͡s‿ˈstuləm")
	self:check_pron("надзо́р", "nɐd͡zˈzor")
	self:check_pron("отсю́да", "ɐtʲ͡sʲˈsʲudə")
	self:check_pron("отсу́да", "ɐt͡sˈsudə", "отсю́да")
	self:check_pron("вѐт/слу́жба", "ˌvʲet͡sˈsluʐbə", "вѐтслу́жба")
	self:check_pron("куро́ртник", "kʊˈrort⁽ʲ⁾nʲɪk")
	self:check_pron("сболтнёшь", "zbɐlt⁽ʲ⁾ˈnʲɵʂ")
	self:check_pron("сболтну́ть", "zbɐltˈnutʲ")
	self:check_pron("спу́тник", "ˈsputʲnʲɪk")
	self:check_pron("расчерти́ть", "rəɕt͡ɕɪrˈtʲitʲ")
	self:check_pron("убе́жищa", "ʊˈbʲeʐɨɕːə")
	self:check_pron("уда́ча", "ʊˈdat͡ɕə")
	self:check_pron("тро́лль", "ˈtrolʲ")
	self:check_pron("подча́с", "pɐˈt͡ɕːas")
	self:check_pron("в ссо́ри", "ˈf‿sːorʲɪ", "в ссо́ре")
	-- self:check_pron("четырё̀хле́тний", "t͡ɕɪtɨˌrʲɵxˈlʲet⁽ʲ⁾nʲɪj") -- should there be a syllable boundary between x and l?
	self:check_pron("подтрибу́нный", "pətːrʲɪˈbunːɨj")
	self:check_pron("што́-то", "ˈʂto‿tə", "что́-то")
	self:check_pron("не всё то зо́лото", "nʲɪ‿ˈfsʲɵ to ˈzolətə")
	self:check_pron("не по нутру́", "nʲɪ‿pə‿nʊtˈru")
	self:check_pron("в то вре́мя как", "ˈf‿to ˈvrʲemʲə kak")
	self:check_pron("не к ме́сту", "nʲɪ‿k‿ˈmʲestʊ")
	self:check_pron("де́сять за́поведей", "ˈdʲesʲɪdʲ͡zʲ ˈzapəvʲɪdʲɪj")
	self:check_pron("мно́го бу́дешь знать", "ˈmnoɡə ˈbudʲɪʐ znatʲ")
	self:check_pron("вою́ю", "vɐˈjʉjʊ")
	self:check_pron("безъя́тие", "bʲɪzˈjætʲɪjə")
	self:check_pron("То́кио", "ˈtokʲɪo")
	self:check_pron("розе́ттский ка́мень", "rɐˈzʲet͡skʲɪj ˈkamʲɪnʲ")
	self:check_pron("от я́блони", "ɐt‿ˈjablənʲɪ")
	self:check_pron("от А́ни", "ɐˈt‿anʲɪ")
	self:check_pron("дама́сский", "dɐˈmasːkʲɪj")
	self:check_pron("ельча́нин", "(j)ɪlʲˈt͡ɕænʲɪn")
	self:check_pron("коменда́нтский ча́с", "kəmʲɪnˈdan(t)skʲɪj ˈt͡ɕas")
	self:check_pron("а̀нгло-норма́ннский", "ˌanɡlə nɐrˈmanskʲɪj")
	self:check_pron("исла́ндский", "ɪsˈlan(t)skʲɪj")
	self:check_pron("коопера́ция", "kɐɐpʲɪˈrat͡sɨjə")
	self:check_pron("съе́ӂӂая", "ˈsjeʑːɪjə", "съе́зжая")
	self:check_pron("сѣдло́", "sʲɪdˈlo")
	self:check_pron("сѣ̈дла", "ˈsʲɵdlə")
	self:check_pron("мне жа́рко", "mnʲe ˈʐarkə")
	self:check_pron("на вку́с и на цвет това́рищей нет", "nɐ‿ˈfkus i nɐ‿ˈt͡svʲet tɐˈvarʲɪɕːɪj nʲet")
	self:check_pron("ма́стер на все ру́ки", "ˈmasʲtʲɪr nɐ‿ˈfsʲe ˈrukʲɪ")
	self:check_pron("мля", "mlʲa")
	self:check_pron("четырё̀хзвёздный", "t͡ɕɪtɨˌrʲɵɣzˈvʲɵznɨj")
	self:check_pron("сегрегациони́сский", "sʲɪɡrʲɪɡət͡sɨɐˈnʲisːkʲɪj", "сегрегациони́стский")
	self:check_pron("сегрегациони́стский", "sʲɪɡrʲɪɡət͡sɨɐˈnʲist͡skʲɪj")
	self:check_pron("пья́нка", "ˈp⁽ʲ⁾jankə")
	self:check_pron("нѐореали́зм", "ˌnʲeərʲɪɐˈlʲizm")
	self:check_pron("ре́гентша", "ˈrʲeɡʲɪnt͡ʂʂə")
	self:check_pron("нра́вственный", "ˈnrafstvʲɪn(ː)ɨj")
	self:check_pron("што́-лѝбо", "ˈʂto ˌlʲibə", "что́-лѝбо")
	self:check_pron("гроздь", "ɡrosʲtʲ")
	self:check_pron("ружьё", "rʊʐˈjɵ")
	self:check_pron("фильм", "fʲilʲm")
	self:check_pron("взаѝмопонима́ние", "vzɐˌiməpənʲɪˈmanʲɪjə")
	self:check_pron("скамья́", "skɐm⁽ʲ⁾ˈja")
	self:check_pron("славянофи́льство", "sləvʲɪnɐˈfʲilʲstvə")
	self:check_pron("сельдь", "sʲelʲtʲ")
	self:check_pron("секво́йя", "sʲɪkˈvojːə")
	self:check_pron("ро́жью", "ˈroʐjʊ")
	self:check_pron("Ю̀жно-Африка́нская Респу́блика", "ˌjuʐnə ɐfrʲɪˈkanskəjə rʲɪˈspublʲɪkə")
	self:check_pron("Дза̀уджика́у", "ˌd͡zzaʊd͡ʐʐɨˈkaʊ")
	self:check_pron("Вели́кая Арме́ния", "vʲɪˈlʲikəjə ɐrˈmʲenʲɪjə")
	self:check_pron("Асунсьо́н", "ɐsʊn⁽ʲ⁾ˈsʲjɵn")
	self:check_pron("Амударья́", "ɐmʊdɐˈrʲja")
	self:check_pron("та́ять", "ˈta(j)ɪtʲ")
	self:check_pron("Арха́нгельск", "ɐrˈxanɡʲɪlʲsk")
	self:check_pron("нецелесообра́зный", "nʲɪt͡sɨlʲɪsɐɐbˈraznɨj")
	self:check_pron("тьфу", "tʲfu")
	self:check_pron("съезд", "sjest")
	self:check_pron("съёмка", "ˈsjɵmkə")
	self:check_pron("предвкуше́ние", "prʲɪtfkʊˈʂɛnʲɪjə")
	self:check_pron("файрво́лл", "fɐjrˈvol")
	self:check_pron("элѐктроэнэ́ргия", "ɨˌlʲektrəɨˈnɛrɡʲɪjə","электроэне́ргия")
	self:check_pron("нало̀гоплате́льщик", "nɐˌloɡəplɐˈtʲelʲɕːɪk","налогоплате́льщик")
	self:check_pron("НЭП", "nɛp")
	self:check_pron("Вьентья́н", "vʲjɪnʲˈtʲjan")
	self:check_pron("шпиль", "ʂpʲilʲ")
	self:check_pron("ка-гэ-бэ́", "ka ɡɛ ˈbɛ", "КГБ")
	self:check_pron("презре́нный", "prʲɪzˈrʲenːɨj")
	self:check_pron("несоверше́нный", "nʲɪsəvʲɪrˈʂɛnːɨj")
	self:check_pron("пятсо́т", "pʲɪt͡sˈsot", "пятьсо́т")
	self:check_pron("шестьдеся́т", "ʂɨzʲdʲɪˈsʲat")
	self:check_pron("пятьдеся́т", "pʲɪdʲɪˈsʲat")
	self:check_pron("сʔу́женный", "ˈsʔuʐɨn(ː)ɨj", "су́женный")
	self:check_pron("съу́женный", "ˈsʔuʐɨn(ː)ɨj", "су́женный")
	self:check_pron("воӂӂа́", "vɐˈʑːa", "вожжа́")
	self:check_pron("дро́ӂӂи", "ˈdroʑːɪ", "дро́жжи")
	self:check_pron("погля́дывать", "pɐˈɡlʲadɨvətʲ")
	self:check_pron("до встре́чи", "dɐ‿ˈfstrʲet͡ɕɪ")
	self:check_pron("варьи́ровать", "vɐˈrʲjirəvətʲ")
	self:check_pron("юла́", "jʊˈla")
	self:check_pron("валя́ться", "vɐˈlʲat͡sːə")
	self:check_pron("подде́ржка", "pɐˈdʲːerʂkə")
	self:check_pron("сверхинтере́сный", "svʲɪrxɨnʲtʲɪˈrʲesnɨj")
	self:check_pron("вещдо́к", "vʲɪʑːˈdok")
	self:check_pron("яйцо́", "(j)ɪjˈt͡so")
	self:check_pron("ещё", "(j)ɪˈɕːɵ")
	self:check_pron("за́яц", "ˈza(j)ɪt͡s")
	self:check_pron("отдохну́ть", "ɐdːɐxˈnutʲ")
	self:check_pron("до́чь бы", "ˈdod͡ʑ‿bɨ")
	self:check_pron("де́йственный", "ˈdʲejstvʲɪn(ː)ɨj")
	self:check_pron("я", "ja")
	self:check_pron("дождь", "doʂtʲ")
	self:check_pron("дощ", "doɕː", "дождь")
	self:check_pron("ночь", "not͡ɕ")
	self:check_pron("смеёшься", "smʲɪˈjɵʂs⁽ʲ⁾ə")
	self:check_pron("ничья́", "nʲɪˈt͡ɕja")
	self:check_pron("не пла́чьте", "nʲɪ‿ˈplat͡ɕtʲə")
	self:check_pron("аа́к", "ɐˈak")
	self:check_pron("аа́м", "ɐˈam")
	self:check_pron("аа́нгич", "ɐˈanɡʲɪt͡ɕ")
	self:check_pron("ааро́новец", "ɐɐˈronəvʲɪt͡s")
	self:check_pron("ааро́новщина", "ɐɐˈronəfɕːɪnə")
	self:check_pron("а́ба", "ˈabə")
	self:check_pron("абава́н", "ɐbɐˈvan", "аба-ва́н")
	self:check_pron("абавуа́", "ɐbəvʊˈa", "аба-вуа́")
	self:check_pron("абажу́р", "ɐbɐˈʐur")
	self:check_pron("аба́з", "ɐˈbas")
	self:check_pron("абаза́", "ɐbɐˈza")
	self:check_pron("абази́н", "ɐbɐˈzʲin")
	self:check_pron("абази́нка", "ɐbɐˈzʲinkə")
	self:check_pron("абази́я", "ɐbɐˈzʲijə")
	self:check_pron("аба́к", "ɐˈbak")
	self:check_pron("абака́", "ɐbɐˈka")
	self:check_pron("абако́ст", "ɐbɐˈkost", "аба-ко́ст")
	self:check_pron("абаку́мыч", "ɐbɐˈkumɨt͡ɕ")
	self:check_pron("Аба́лкин", "ɐˈbalkʲɪn")
	self:check_pron("абало́н", "ɐbɐˈlon")
	self:check_pron("абандо́н", "ɐbɐnˈdon")
	self:check_pron("абарогно́з", "ɐbərɐɡˈnos")
	self:check_pron("абато́н", "ɐbɐˈton")
	self:check_pron("абаша́", "ɐbɐˈʂa")
	self:check_pron("абба́си", "ɐˈbasʲɪ")
	self:check_pron("абба́т", "ɐˈbat")
	self:check_pron("аббати́са", "ɐbɐˈtʲisə")
	self:check_pron("абба́тство", "ɐˈbat͡stvə")
	self:check_pron("аббревиату́ра", "ɐbrʲɪvʲɪɐˈturə")
	self:check_pron("аббревиа́ция", "ɐbrʲɪvʲɪˈat͡sɨjə")
	self:check_pron("абда́л", "ɐbˈdal")
	self:check_pron("абдери́т", "ɐbdʲɪˈrʲit")
	self:check_pron("абде́ст", "ɐbˈdʲest")
	self:check_pron("абдика́ция", "ɐbdʲɪˈkat͡sɨjə")
	self:check_pron("абдо́мен", "ɐbˈdomʲɪn")
	self:check_pron("абдукта́нт", "ɐbdʊkˈtant")
	self:check_pron("абду́ктор", "ɐbˈduktər")
	self:check_pron("абду́кция", "ɐbˈdukt͡sɨjə")
	self:check_pron("абэвэ́га", "ɐbɨˈvɛɡə")
	self:check_pron("а́белев", "ˈabʲɪlʲɪf")
	self:check_pron("абе́лия", "ɐˈbʲelʲɪjə")
	self:check_pron("абельмо́ш", "ɐbʲɪlʲˈmoʂ")
	self:check_pron("аберра́ция", "ɐbʲɪˈrat͡sɨjə")
	self:check_pron("абе́с", "ɐˈbʲes")
	self:check_pron("абесси́в", "ɐbʲɪˈsʲif")
	self:check_pron("абза́ц", "ɐbˈzat͡s")
	self:check_pron("абиети́н", "ɐbʲɪ(j)ɪˈtʲin")
	self:check_pron("аби́лка", "ɐˈbʲilkə")
	self:check_pron("абисса́ль", "ɐbʲɪˈsalʲ")
	self:check_pron("абисси́нец", "ɐbʲɪˈsʲinʲɪt͡s")
	self:check_pron("абитурие́нт", "ɐbʲɪtʊrʲɪˈjent")
	self:check_pron("абитурие́нтка", "ɐbʲɪtʊrʲɪˈjentkə")
	self:check_pron("аблакта́ция", "ɐblɐkˈtat͡sɨjə")
	self:check_pron("аблакти́рование", "ɐblɐkˈtʲirəvənʲɪjə")
	self:check_pron("аблактиро́вка", "ɐbləktʲɪˈrofkə")
	self:check_pron("аблати́в", "ɐblɐˈtʲif")
	self:check_pron("абла́ут", "ɐbˈlaʊt")
	self:check_pron("абляти́в", "ɐblʲɪˈtʲif")
	self:check_pron("абля́ция", "ɐbˈlʲat͡sɨjə")
	self:check_pron("аболициони́зм", "ɐbəlʲɪt͡sɨɐˈnʲizm")
	self:check_pron("аболициони́ст", "ɐbəlʲɪt͡sɨɐˈnʲist")
	self:check_pron("аболициони́стка", "ɐbəlʲɪt͡sɨɐˈnʲistkə")
	self:check_pron("абонеме́нт", "ɐbənʲɪˈmʲent")
	self:check_pron("абоне́нт", "ɐbɐˈnʲent")
	self:check_pron("аборда́ж", "ɐbɐrˈdaʂ")
	self:check_pron("абориге́н", "ɐbərʲɪˈɡʲen")
	self:check_pron("або́рт", "ɐˈbort")
	self:check_pron("абрази́в", "ɐbrɐˈzʲif")
	self:check_pron("абрази́вность", "ɐbrɐˈzʲivnəsʲtʲ")
	self:check_pron("абра́зия", "ɐbˈrazʲɪjə")
	self:check_pron("абракада́бра", "ɐbrəkɐˈdabrə")
	self:check_pron("абрико́с", "ɐbrʲɪˈkos")
	self:check_pron("абрикоти́н", "ɐbrʲɪkɐˈtʲin")
	self:check_pron("а́брис", "ˈabrʲɪs")
	self:check_pron("аброга́ция", "ɐbrɐˈɡat͡sɨjə")
	self:check_pron("абса́нс", "ɐpˈsans")
	self:check_pron("абси́да", "ɐpˈsʲidə")
	self:check_pron("абсолю́т", "ɐpsɐˈlʲut")
	self:check_pron("абсолютиза́ция", "ɐpsəlʲʉtʲɪˈzat͡sɨjə")
	self:check_pron("абсолютизи́рование", "ɐpsəlʲʉtʲɪˈzʲirəvənʲɪjə")
	self:check_pron("абсолютизи́ровать", "ɐpsəlʲʉtʲɪˈzʲirəvətʲ")
	self:check_pron("абсолюти́зм", "ɐpsəlʲʉˈtʲizm")
	self:check_pron("абсолюти́ст", "ɐpsəlʲʉˈtʲist")
	self:check_pron("абсолю́тность", "ɐpsɐˈlʲutnəsʲtʲ")
	self:check_pron("абсолю́тный", "ɐpsɐˈlʲutnɨj")
	self:check_pron("абсорба́т", "ɐpsɐrˈbat")
	self:check_pron("абсорбе́нт", "ɐpsɐrˈbʲent")
	self:check_pron("абсо́рбер", "ɐpˈsorbʲɪr")
	self:check_pron("абсорби́рование", "ɐpsɐrˈbʲirəvənʲɪjə")
	self:check_pron("абсорби́ровать", "ɐpsɐrˈbʲirəvətʲ")
	self:check_pron("абсорби́роваться", "ɐpsɐrˈbʲirəvət͡sə")
	self:check_pron("абсо́рбция", "ɐpˈsorpt͡sɨjə")
	self:check_pron("абстине́нт", "ɐpsʲtʲɪˈnʲent")
	self:check_pron("абстине́нция", "ɐpsʲtʲɪˈnʲent͡sɨjə")
	self:check_pron("абстраги́рование", "ɐpstrɐˈɡʲirəvənʲɪjə")
	self:check_pron("абстраги́ровать", "ɐpstrɐˈɡʲirəvətʲ")
	self:check_pron("абстра́кт", "ɐpˈstrakt")
	self:check_pron("абстра́ктность", "ɐpˈstraktnəsʲtʲ")
	self:check_pron("абстра́ктный", "ɐpˈstraktnɨj")
	self:check_pron("абстракциони́зм", "ɐpstrəkt͡sɨɐˈnʲizm")
	self:check_pron("абстракциони́ст", "ɐpstrəkt͡sɨɐˈnʲist")
	self:check_pron("абстра́кция", "ɐpˈstrakt͡sɨjə")
	self:check_pron("абсу́рд", "ɐpˈsurt")
	self:check_pron("абсурди́зм", "ɐpsʊrˈdʲizm")
	self:check_pron("абсурди́ст", "ɐpsʊrˈdʲist")
	self:check_pron("абсу́рдность", "ɐpˈsurdnəsʲtʲ")
	self:check_pron("абсу́рдный", "ɐpˈsurdnɨj")
	self:check_pron("абсце́сс", "ɐpˈst͡sɛs")
	self:check_pron("абсци́сса", "ɐpˈst͡sɨsːə")
	self:check_pron("абули́я", "ɐbʊˈlʲijə")
	self:check_pron("абха́з", "ɐpˈxas")
	self:check_pron("аванга́рд", "ɐvɐnˈɡart")
	self:check_pron("аванпо́ст", "ɐvɐnˈpost")
	self:check_pron("ава́нс", "ɐˈvans")
	self:check_pron("авансце́на", "ɐvɐnˈst͡sɛnə")
	self:check_pron("авантю́ра", "ɐvɐnʲˈtʲurə")
	self:check_pron("авантюри́зм", "ɐvənʲtʲʉˈrʲizm")
	self:check_pron("авантюри́ст", "ɐvənʲtʲʉˈrʲist")
	self:check_pron("авантюри́стка", "ɐvənʲtʲʉˈrʲistkə")
	self:check_pron("ава́рец", "ɐˈvarʲɪt͡s")
	self:check_pron("ава́рия", "ɐˈvarʲɪjə")
	self:check_pron("авата́р", "ɐvɐˈtar")
	self:check_pron("авгу́р", "ɐvˈɡur")
	self:check_pron("а́вгуст", "ˈavɡʊst")
	self:check_pron("А́вель", "ˈavʲɪlʲ")
	self:check_pron("авеню́", "ɐvʲɪˈnʲu")
	self:check_pron("авиаба́за", "ɐvʲɪɐˈbazə")
	self:check_pron("авиабиле́т", "ɐvʲɪəbʲɪˈlʲet")
	self:check_pron("авиабрига́да", "ɐvʲɪəbrʲɪˈɡadə")
	self:check_pron("авиагоризо́нт", "ɐvʲɪəɡərʲɪˈzont")
	self:check_pron("авиадиви́зия", "ɐvʲɪədʲɪˈvʲizʲɪjə")
	self:check_pron("авиазвено́", "ɐvʲɪəzvʲɪˈno")
	self:check_pron("авиакомпа́ния", "ɐvʲɪəkɐmˈpanʲɪjə")
	self:check_pron("авиако́рпус", "ɐvʲɪɐˈkorpʊs")
	self:check_pron("авиали́ния", "ɐvʲɪɐˈlʲinʲɪjə")
	self:check_pron("авиама́тка", "ɐvʲɪɐˈmatkə")
	self:check_pron("авианалёт", "ɐvʲɪənɐˈlʲɵt")
	self:check_pron("авиано́сец", "ɐvʲɪɐˈnosʲɪt͡s")
	self:check_pron("авиаотря́д", "ɐvʲɪɐɐtˈrʲat")
	self:check_pron("авиапо́лк", "ɐvʲɪɐˈpolk")
	self:check_pron("авиапо́чта", "ɐvʲɪɐˈpot͡ɕtə")
	self:check_pron("авиапредприя́тие", "ɐvʲɪəprʲɪtprʲɪˈjætʲɪjə")
	self:check_pron("авиа́тор", "ɐvʲɪˈatər")
	self:check_pron("авиауда́р", "ɐvʲɪəʊˈdar")
	self:check_pron("авиа́ция", "ɐvʲɪˈat͡sɨjə")
	self:check_pron("ага́р-ага́р", "ɐˈɡar ɐˈɡar")
	self:check_pron("заво́д подря́дчик", "zɐˈvot pɐdˈrʲæt͡ɕːɪk", "заво́д-подря́дчик")
	self:check_pron("пингпо́нг", "pʲɪnkˈponk", "пинг-по́нг")
	self:check_pron("пти́ца-адъюта́нт", "ˈptʲit͡sə ɐdjʊˈtant")
	self:check_pron("в чём де́ло", "ˈf‿t͡ɕɵm ˈdʲelə")
	self:check_pron("голосовы́е свя́зки", "ɡələsɐˈvɨjə ˈsvʲaskʲɪ")
	self:check_pron("да́мы и господа́", "ˈdamɨ i ɡəspɐˈda")
	self:check_pron("ссо́ра", "ˈsːorə")
	self:check_pron("введе́ние", "vʲːɪˈdʲenʲɪjə")
	self:check_pron("ввод", "vːot")
	self:check_pron("сча́стье", "ˈɕːæsʲtʲjə")
	self:check_pron("гру́зчик", "ˈɡruɕːɪk")
	self:check_pron("то́нна", "ˈtonːə")
	self:check_pron("по́ле", "ˈpolʲə")
	self:check_pron("наедине́", "nə(j)ɪdʲɪˈnʲe")
	self:check_pron("поеди́нок", "pə(j)ɪˈdʲinək")
	self:check_pron("степь", "sʲtʲepʲ")
	self:check_pron("здесь", "zʲdʲesʲ")
	self:check_pron("по́нчик", "ˈponʲt͡ɕɪk")
	self:check_pron("ка́менщик", "ˈkamʲɪnʲɕːɪk")
	self:check_pron("снег", "s⁽ʲ⁾nʲek")
	self:check_pron("злить", "z⁽ʲ⁾lʲitʲ")
	self:check_pron("подня́ть", "pɐdʲˈnʲætʲ")
	self:check_pron("отня́ть", "ɐtʲˈnʲætʲ")
	self:check_pron("ви́нтик", "ˈvʲinʲtʲɪk")
	self:check_pron("пе́нсия", "ˈpʲen⁽ʲ⁾sʲɪjə")
	self:check_pron("расщепи́ть", "rəɕːɪˈpʲitʲ")
	self:check_pron("сшить", "ʂːɨtʲ")
	self:check_pron("сжать", "ʐːatʲ")
	self:check_pron("отцепи́ть", "ɐt͡sːɨˈpʲitʲ")
	self:check_pron("отчёт", "ɐˈt͡ɕːɵt")
	self:check_pron("здра́ствуй", "ˈzdrastvʊj", "здра́вствуй")
	self:check_pron("чу́ствовать", "ˈt͡ɕustvəvətʲ", "чу́вствовать")
	self:check_pron("по́здно", "ˈpoznə")
	self:check_pron("уздцы́", "ʊˈst͡sɨ")
	self:check_pron("со́лнце", "ˈsont͡sə")
	self:check_pron("голла́ндцы", "ɡɐˈlant͡sɨ")
	self:check_pron("ланша́фт", "lɐnˈʂaft", "ландша́фт")
	self:check_pron("рентге́н", "rʲɪnˈɡʲen")
	self:check_pron("се́рдце", "ˈsʲert͡sə")
	self:check_pron("сердчи́шко", "sʲɪrˈt͡ɕiʂkə")
	self:check_pron("счастли́вый", "ɕːɪs⁽ʲ⁾ˈlʲivɨj")
	self:check_pron("ме́стный", "ˈmʲesnɨj")
	self:check_pron("улыба́ется", "ʊlɨˈba(j)ɪt͡sə")
	self:check_pron("чёрный", "ˈt͡ɕɵrnɨj")
	self:check_pron("у́зко", "ˈuskə")
end

return tests

-- For Vim, so we get 4-space tabs
-- vim: set ts=4 sw=4 noet:
