local data = {}

data.variety_list = {
	["MSC"] = { "[[w:Standard Chinese|MSC]]", "cmn", "Pinyin" },
		["M-BJ"] = { "[[w:Beijing dialect|Beijing Mandarin]]", "cmn-bei", "Pinyin" },
		["M-TW"] = { "[[w:Taiwanese Mandarin|Taiwanese Mandarin]]", "cmn-TW", "Pinyin" },
		["M-MY"] = { "[[w:Malaysian Mandarin|Malaysian Mandarin]]", "cmn-MY", "Pinyin" },
		["M-SG"] = { "[[w:Singaporean Mandarin|Singaporean Mandarin]]", "cmn-SG", "Pinyin" },
		["M-PH"] = { "[[w:Mandarin Chinese in the Philippines|Philippine Mandarin]]", "cmn-PH", "Pinyin" },
		["M-TJ"] = { "[[w:Tianjin dialect|Tianjin Mandarin]]", "cmn-tia", "Pinyin" },
		["M-NE"] = { "[[w:Northeastern Mandarin|Northeastern Mandarin]]", "cmn-noe", "Pinyin" },
		["M-CP"] = { "[[w:Central Plains Mandarin|Central Plains Mandarin]]", "cmn-cep", "Pinyin"},
		["M-GZ"] = { "[[w:Xi'an dialect|Guanzhong Mandarin]]", "cmn-gua", "Pinyin"}, --Guanzhong
		["M-LY"] = { "[[w:Lanyin Mandarin|Lanyin Mandarin]]", "cmn-lan", "Pinyin"},
		["M-S"]  = { "[[w:Sichuanese dialects|Sichuanese]]", "zhx-sic", "Sichuanese Pinyin" },
		["M-NJ"] = { "[[w:Nanjing dialect|Nanjing Mandarin]]", "cmn-nan", "Nankinese Pinyin" },
		["M-YZ"] = { "[[w:Yangzhou dialect|Yangzhou Mandarin]]", "cmn-yan", "IPA" }, --IPA as a placeholder
		["M-W"]  = { "[[w:Wuhan dialect|Wuhanese]]", "cmn-wuh", "IPA" },
		["M-GL"]  = { "[[w:zh:桂林話|Guilin Mandarin]]", "cmn-gui", "IPA" }, --IPA as a placeholder
		["M-XN"]  = { "Xining Mandarin", "cmn-xin", "IPA" }, --IPA as a placeholder
		["M-UIB"] = { "[[w:Mandarin Chinese|dialectal Mandarin]]", "cmn", "Pinyin" }, -- UIB stands for "unidentified Beijingesque"; this is only used for dialects with similar phonology to one of Beijing dialect or MSC
		["M-DNG"] = { "[[w:Dungan language|Dungan]]", "dng", "Cyrillic" },
	
	["CL"] = { "[[w:Classical Chinese|Classical Chinese]]", "cmn", "Pinyin" },
		["CL-TW"] = { "[[w:Classical Chinese|Classical Chinese]]", "cmn", "Pinyin ([[w:Taiwanese Mandarin|Taiwanese Mandarin]])" },
		["CL-C"] = { "[[w:Classical Chinese|Classical Chinese]]", "yue", "Jyutping" },
		["CL-C-T"] = { "[[w:Classical Chinese|Classical Chinese]]", "zhx-tai", "Wiktionary" },
		["CL-VN"] = { "[[w:Literary Chinese in Vietnam|Vietnamese Literary Sinitic]]", "vi", "[[w:Sino-Vietnamese vocabulary|Sino-Vietnamese]]" },
		["CL-KR"] = { "[[w:Chinese-language literature of Korea|Korean Literary Sinitic]]", "ko", "[[w:Sino-Korean vocabulary|Sino-Korean]]" },
		["CL-C"] = { "[[w:Classical Chinese|Classical Chinese]]", "yue", "Jyutping" },
		["CL-PC"] = { "[[w:Old Chinese|Pre-Classical Chinese]]", "cmn", "Pinyin" },
		["CL-L"] = { "[[w:Literary Chinese|Literary Chinese]]", "cmn", "Pinyin"},

	["CI"] = { "[[w:Ci (poetry)|Ci]]", "cmn", "Pinyin" },
	
	["WVC"] = { "[[w:Written vernacular Chinese|Written Vernacular Chinese]]", "cmn", "Pinyin" },
		["WVC-C"] = { "[[w:Written vernacular Chinese|Written Vernacular Chinese]]", "yue", "Jyutping" },
		["WVC-C-T"] = { "[[w:Written vernacular Chinese|Written Vernacular Chinese]]", "zhx-tai", "Wiktionary" },

	["C"] = { "[[w:Cantonese|Cantonese]]", "yue", "Jyutping" },
		["C-GZ"] = { "[[w:Cantonese|Guangzhou Cantonese]]", "yue", "Jyutping" },
		["C-LIT"] = { "[[w:Cantonese|Literary Cantonese]]", "yue", "Jyutping" },
		["C-HK"] = { "[[w:Hong Kong Cantonese|Hong Kong Cantonese]]", "yue", "Jyutping" },
		["C-T"] = { "[[w:Taishanese|Taishanese]]", "zhx-tai", "Wiktionary" },
		["C-DZ"] = { "[[w:Danzhou dialect|Danzhou dialect]]", "zhx-dan", "IPA" }, --IPA as a placeholder

	["J"] = { "[[w:Jin Chinese|Jin]]", "cjy", "[[Wiktionary:About Chinese/Jin|Wiktionary]]" },
		
	["MB"] = { "[[w:Northern Min|Northern Min]]", "mnp", "[[w:Kienning Colloquial Romanized|Kienning Colloquial Romanized]]" },
	
	["MD"] = { "[[w:Eastern Min|Eastern Min]]", "cdo", "[[w:Bàng-uâ-cê|Bàng-uâ-cê]] / IPA" },
	
	["MN"] = { "[[w:Hokkien|Hokkien]]", "nan-hbl", "[[w:Pe̍h-ōe-jī|Pe̍h-ōe-jī]]" },
		["TW"] = { "[[w:Taiwanese Hokkien|Taiwanese Hokkien]]", "nan-hbl", "[[w:Pe̍h-ōe-jī|Pe̍h-ōe-jī]]" },
		["MN-PN"] = { "[[w:Penang Hokkien|Penang Hokkien]]", "nan-pen", "[[w:Pe̍h-ōe-jī|Pe̍h-ōe-jī]]" },
		["MN-PH"] = { "[[w:Philippine Hokkien|Philippine Hokkien]]", "nan-hbl-PH", "[[w:Pe̍h-ōe-jī|Pe̍h-ōe-jī]]" },
		["MN-T"] = { "[[w:Teochew dialect|Teochew]]", "nan-tws", "[[w:Peng\'im|Peng\'im]]" },
		["MN-L"] = { "[[w:Leizhou Min|Leizhou Min]]", "nan-luh", "Leizhou Pinyin" },
		["MN-HLF"] = { "[[w:Haklau Min|Haklau Min]]", "nan-hlh", "IPA" }, --IPA as a placeholder
		["MN-H"] = { "[[w:Hainanese|Hainanese]]", "nan-hnm", "[[w:Guangdong Romanization|Guangdong Romanization]]" },
		
	["W"] = { "[[w:Wu Chinese|Wu]]", "wuu", "[[Wiktionary:About Chinese/Wu|Wugniu]]" },
		["SH"] = { "[[w:Shanghainese|Shanghainese]]", "wuu", "[[Wiktionary:About Chinese/Wu|Wugniu]]" },
		["W-SZ"] = { "[[w:Suzhounese|Suzhounese]]", "wuu", "[[Wiktionary:About Chinese/Wu|Wugniu]]" }, -- wuu-sz?
		["W-HZ"] = { "[[w:Hangzhounese|Hangzhounese]]", "wuu", "[[Wiktionary:About Chinese/Wu|Wugniu]]" }, -- wuu-hz?
		["W-CM"] = { "[[w:Shadi dialect|Shadi Wu]]", "wuu", "[[Wiktionary:About Chinese/Wu|Wugniu]]" }, -- wuu-cm? including Chongming, Haimen, Changyinsha etc
		["W-NB"] = { "[[w:Ningbo dialect|Ningbonese]]", "wuu", "[[Wiktionary:About Chinese/Wu|Wugniu]]" },
		["W-N"] = { "[[w:Northern Wu|Northern Wu]]", "wuu", "[[Wiktionary:About Chinese/Wu|Wugniu]]" }, -- general northern wu, incl. transitionary varieties
		["W-WZ"] = { "[[w:Wenzhou dialect|Wenzhounese]]", "wuu-wen", "[[Wiktionary:About Chinese/Wu|Wugniu]]" }, -- wuu-wz?
		
	["G"] = { "[[w:Gan Chinese|Gan]]", "gan", "[[Wiktionary:About Chinese/Gan|Wiktionary]]" },

	["X"] = { "[[w:Xiang Chinese|Xiang]]", "hsn", "[[Wiktionary:About Chinese/Xiang|Wiktionary]]" },
		
	["H"] = { "[[w:Sixian dialect|Sixian Hakka]]", "hak", "[[w:Pha̍k-fa-sṳ|Pha̍k-fa-sṳ]]" },
		["H-HL"] = { "[[w:Hailu dialect|Hailu Hakka]]", "hak", "[[w:Taiwanese Hakka Romanization System|Taiwanese Hakka Romanization System]]" },
		["H-DB"] = { "[[w:zh:臺灣客家語#大埔腔|Dabu Hakka]]", "hak", "[[w:Taiwanese Hakka Romanization System|Taiwanese Hakka Romanization System]]" },
        ["H-MX"] = { "[[w:Meixian dialect|Meixian Hakka]]", "hak", "[[w:Pinfa|Hakka Transliteration Scheme]]" },
		["H-MY-HY"] = { "Malaysian Huiyang Hakka", "hak", "IPA" }, --IPA as a placeholder
		["H-EM"] = { "[[w:Hakka Chinese|Hakka]]", "hak", "IPA" }, --Early Modern Hakka, IPA as a placeholder
		["H-ZA"] = { "[[w:zh:詔安客語|Zhao'an Hakka]]", "hak", "[[w:Taiwanese Hakka Romanization System|Taiwanese Hakka Romanization System]]" },
	
	["WX"] = { "[[w:Waxiang Chinese|Waxiang]]", "wxa", "IPA" },
}

-- This is used to normalize/canonicalize variety codes that should be treated the same. In this case, all Hokkien
-- varieties use Pe̍h-ōe-jī and should behave the same for pron_correction and other purposes. Similarly, many
-- Mandarin varieties use standard Pinyin, etc.
data.variety_code_normalization = {
	-- Mandarin
	["cmn-bei"] = "cmn",
	["cmn-TW"] = "cmn",
	["cmn-MY"] = "cmn",
	["cmn-SG"] = "cmn",
	["cmn-PH"] = "cmn",
	["cmn-tia"] = "cmn",
	["cmn-noe"] = "cmn",
	["cmn-cep"] = "cmn",
	["cmn-gua"] = "cmn",
	["cmn-lan"] = "cmn",
	-- Hokkien
	["nan-pen"] = "nan-hbl",
	["nan-hbl-PH"] = "nan-hbl",
}

data.punctuation = {
	["，"] = ",",	["。"] = ".",	["、"] = ",",
	["？"] = "?",	["！"] = "!",
	
	["《"] = "“",	["》"] = "”",
	["〈"] = "‘",	["〉"] = "’",
	["『"] = "‘",	["』"] = "’",
	["「"] = "“",	["」"] = "”",
	["“"] = "“",	["”"] = "”",
	
	["（"] = "(",	["）"] = ")",
	["；"] = ";",	["："] = ":",
	["|"] = "|",	["—"] = "-",	["～"] = "~",	["——"] = "—",
	["·"] = " ",	["…"] = "...",
	["．"] = ".",

	["　"] = ",",
	["⋯"] = "...",  ["⋯⋯"] = "...",
	
	["<br>"] = "<br>", ["<br/>"] = "<br>",
}

local CE = '<small class="ce-date">[[Appendix:Glossary#CE|<span title="Glossary and display preference">CE</span>]]</small>'
local BCE = '<small class="ce-date">[[Appendix:Glossary#BCE|<span title="Glossary and display preference">BCE</span>]]</small>'
local circa = "''[[Appendix:Glossary#c.|c.]]''"

local function format_mao(year, chinese_title, english_title, volume, number) -- volume and number are used to generate links to the Marxists Internet Archive
	return { "MSC",  "'''" .. year .. "''', <span lang=\"zh\" class=\"Hani\">[[w:zh:毛澤東|毛澤東]]</span> ([[w:Mao Zedong|Mao Zedong]]), <span lang=\"zh\" class=\"Hani\">《" .. chinese_title .. "》</span> (" .. english_title .. "), <span lang=\"zh\" class=\"Hani\">《[[w:zh:毛澤東選集|毛澤東選集]]》</span>. English translation based on [https://www.marxists.org/reference/archive/mao/selected-works/volume-" .. volume .. "/mswv" .. volume .. "_" .. number .. ".htm the Foreign Languages Press edition]" }
end

data.ref_list = {
	['Analects']     =  { "CL",  "The ''[[w:Analects|Analects]] of Confucius'', " .. circa .. " 475 – 221 " .. BCE .. ", translated based on [[w:James Legge|James Legge]]'s version" },
	['Analects-W']   =  { "CL",  "The ''[[w:Analects|Analects]] of Confucius'', " .. circa .. " 475 – 221 " .. BCE .. ", Wiktionary translation" },
	['Baihutong']    =  { "CL-L",  "[[w:Ban Gu|Ban Gu]], ''[[w:Bai Hu Tong|The Comprehensive Discussions in the White Tiger Hall]]'', 79 " .. CE },
	['Baihutong-T']    =  { "CL-L",  "[[w:Ban Gu|Ban Gu]], ''[[w:Bai Hu Tong|The Comprehensive Discussions in the White Tiger Hall]]'', 79 " .. CE .. ", translated based on [[w:Tjan Tjoe Som|Tjan Tjoe Som]]'s version" },
	['Baopuzi']    =  { "CL-L",  "[[w:Ge Hong|Ge Hong]], ''[[w:Baopuzi|Baopuzi]]'', 4<sup>th</sup> century " .. CE },
	['Beiji Qianjin Yaofang']  =  { "CL-L",  "[[w:Sun Simiao|Sun Simiao]], ''[[w:Beiji qianjin yaofang|Essential Formulas Worth a Thousand Weights in Gold to Prepare for Emergencies]]'', 652 " .. CE },
	['Beiqishu']     =  { "CL-L",  "The ''[[w:Book of Northern Qi|Book of Northern Qi]]'', by [[w:Li Baiyao|Li Baiyao]], 636 " .. CE },
	['Beishi']       =  { "CL",  circa .. " '''659''' " .. CE .. ", Li Yanshou, ''[[w:History of the Northern Dynasties|History of the Northern Dynasties]]''" },
	['Bencao Gangmu']=  { "CL-L",  "The ''[[w:Compendium of Materia Medica|Compendium of Materia Medica]]'' [Bencao Gangmu], by [[w:Li Shizhen|Li Shizhen]], 1578 " .. CE },
	['Changhenge']   =  { "CL-L",  "'''806''' " .. CE .. ", [[w:Bai Juyi|Bai Juyi]], ''[[wikisource:Song of Everlasting Regret|Song of Everlasting Regret]]''" },
	['Chuci']        =  { "CL",  "The ''[[w:Chu Ci|Verses of Chu]]'', 4<sup>th</sup> century " .. BCE .." – 2<sup>nd</sup> century " .. CE },
	['Chuci-H']      =  { "CL",  "The ''[[w:Chu Ci|Verses of Chu]]'', 4<sup>th</sup> century " .. BCE .." – 2<sup>nd</sup> century " .. CE .. ", translated based on [[w:David Hawkes (sinologist)|David Hawkes']] version" },
	['Chunqiu Fanlu']=  { "CL",  "The ''[[w:Luxuriant Dew of the Spring and Autumn Annals|Luxuriant Dew of the Spring and Autumn Annals]]''" },
	['Daodejing']    =  { "CL",  "''[[w:Tao Te Ching|Tao Te Ching]]'', 4<sup>th</sup> century " .. BCE },
	['Daodejing-L']  =  { "CL",  "''[[w:Tao Te Ching|Tao Te Ching]]'', 4<sup>th</sup> century " .. BCE .. ", translated based on [[w:James Legge|James Legge]]'s version" },
	['Datang Xiyuji']=  { "CL-L",  "[[w:Xuanzang|Xuanzang]], ''[[w:Great Tang Records on the Western Regions|Great Tang Records on the Western Regions]]'', 646 " .. CE },
	['Datang Xiyuji-B']=  { "CL-L",  "[[w:Xuanzang|Xuanzang]], ''[[w:Great Tang Records on the Western Regions|Great Tang Records on the Western Regions]]'', 646 " .. CE .. ", translated based on [[w:Samuel Beal|Samuel Beal]]'s version" },
	['Datang Xiyuji-L']=  { "CL-L",  "[[w:Xuanzang|Xuanzang]], ''[[w:Great Tang Records on the Western Regions|Great Tang Records on the Western Regions]]'', 646 " .. CE .. ", translated based on Li Rongxi's version" },
	['Dongguan Han Ji']=  { "CL",  "''[[w:zh:東觀漢記|Dongguan Han Ji]]'', 1<sup>st</sup> century " .. CE .."– 2<sup>nd</sup> century " .. CE },
	['Dou E Yuan']=  { "WVC",  "'''Yuan Dynasty''', [[w:Guan Hanqing|Guan Hanqing]], ''[[w:The Injustice to Dou E|The Injustice to Dou E]]''" },
	['Erya']         =  { "CL",  "''[[w:Erya|Erya]]'', 5<sup>th</sup> – 2<sup>nd</sup> century " .. BCE },
	['Ernv Yingxiongzhuan'] = { "WVC", "Wenkang, ''[[w:Ernü Yingxiong Zhuan|Ernü Yingxiongzhuan]]'', 1878 " .. CE },
	['Fangyan']      =  { "CL",  "[[w:Yang Xiong (author)|Yang Xiong]], ''[[w:Fangyan|Fangyan]]'', " .. circa .. " 1<sup>st</sup> century " .. BCE },
	['Fangyu Shenglan']      =  { "CL-L",  "''[[w:zh:方輿勝覽|Fangyu Shenglan]]'', " .. circa .. " 13<sup>th</sup> century " .. CE },
	['Fayan']        =  { "CL",  "[[w:Yang Xiong (author)|Yang Xiong]], ''[[w:Fayan (book)|Fa Yan]]'' (''Exemplary Sayings''), 9 " .. CE },
	['Fayan-B']      =  { "CL",  "[[w:Yang Xiong (author)|Yang Xiong]], ''[[w:Fayan (book)|Fa Yan]]'' (''Exemplary Sayings''), 9 " .. CE .. ", translated based on Jeffrey S. Bullock's version" },
	['Fengsu Tongyi']      =  { "CL",  "[[w:Ying Shao|Ying Shao]], ''[[w:Fengsu Tongyi|Fengsu Tongyi]]'' (''Comprehensive Meaning of Customs and Mores''), 195 " .. CE },
    ['Gaosengzhuan']=  { "CL",  "Shi Huijiao, ''[[w:Memoirs of Eminent Monks|Memoirs of Eminent Monks]]'', circa 530 " .. CE },
    ['Gongyangzhuan']=  { "CL",  "''[[w:Gongyang Zhuan|Commentary of Gongyang]]'', " .. circa .. " 206 " .. BCE .. "– 9 " .. CE },
	['Guanyinzi']    =  { "CL",  "''[[w:zh:關尹子|Guanyinzi]]'', time unknown" },
	['Guanzi']       =  { "CL",  "''[[w:Guanzi (text)|Guanzi]]'', 5<sup>th</sup> century " .. BCE .. " to 220 " .. CE  },
	['Gujin Xiaoshuo']=  { "WVC", "[[w:Feng Menglong|Feng Menglong]], ''[[w:Stories Old and New|Stories Old and New]]'', 1620 " .. CE },
    ['Guliangzhuan'] =  { "CL",  "''[[w:Guliang Zhuan|Commentary of Guliang]]'', circa 206 " .. BCE .. "– 9 " .. CE },
	['Guoyu']        =  { "CL",  "''[[w:Guoyu (book)|Guoyu]]'', circa 4<sup>th</sup> century " .. BCE },
	['Hanfeizi']     =  { "CL",  "''[[w:Han Feizi (book)|Han Feizi]]'', circa 2<sup>nd</sup> century " .. BCE },
	['Hanfeizi-L']   =  { "CL",  "''[[w:Han Feizi (book)|Han Feizi]]'', circa 2<sup>nd</sup> century " .. BCE .. ", translated based on [[w:zh:廖文奎|W. K. Liao]]'s version" },
	['Hanshi Waizhuan']    =  { "CL",  "''[[w:Han shi waizhuan|Han shi waizhuan]]'', 1<sup>nd</sup> century " .. BCE },
	['Hanshi Waizhuan-H']  =  { "CL",  "''[[w:Han shi waizhuan|Han shi waizhuan]]'', 1<sup>nd</sup> century " .. BCE .. ", translated based on [[w:James Robert Hightower|James R. Hightower]]'s version" },
	['Hanshu']       =  { "CL",  "The ''[[w:Book of Han|Book of Han]]'', circa 1<sup>st</sup> century " .. CE },
	['Houhanshu']    =  { "CL-L",  "The ''[[w:Book of the Later Han|Book of the Later Han]]'', circa 5<sup>th</sup> century " .. CE },
	['Hongloumeng']  =  { "WVC", "[[w:Cao Xueqin|Cao Xueqin]], ''[[w:Dream of the Red Chamber|Dream of the Red Chamber]]'', mid-18<sup>th</sup> century " .. CE },
	['Huainanzi']    =  { "CL",  "''[[w:Huainanzi|Huainanzi]]'', 2<sup>nd</sup> century " .. BCE },
	['Huangdi Neijing']={ "CL",  "''[[w:Huangdi Neijing|Huangdi Neijing]]'', 4<sup>th</sup> century " .. BCE .. " to 3<sup>rd</sup> century " .. CE },
	['Jinpingmei']   =  { "WVC",  "''[[w:The Plum in the Golden Vase|The Plum in the Golden Vase]]'', circa 1610 " .. CE },
    ['Jinpingmei-R']   =  { "WVC",  "''[[w:The Plum in the Golden Vase|The Plum in the Golden Vase]]'', circa 1610 " .. CE .. ", translated based on [[w:David Tod Roy|David Tod Roy]]'s version" },
	['Jinshi']       =  { "CL-L",  "'''1344''' " .. CE .. ", [[w:Toqto'a (Yuan dynasty)|Toqto'a]] (lead editor), ''[[w:History of Jin|History of Jin]]''" },
	['Jinshu']       =  { "CL-L",  "'''648''' " .. CE .. ", [[w:Fang Xuanling|Fang Xuanling]] (lead editor), ''[[w:Book of Jin|Book of Jin]]''" },
	['Jiutangshu']   =  { "CL-L",  "The ''[[w:Old Book of Tang|Old Book of Tang]]'', 945 " .. CE },
    ['Kongzi Jiayu'] =  { "CL",  "The ''[[w:Kongzi Jiayu|School Sayings of Confucius]]'', " .. circa .. " 206 " .. BCE .. "– 220 " .. CE },
	['Lantingjixu']  =  { "CL-L",  "'''353''' " .. CE .. ", [[w:Wang Xizhi|Wang Xizhi]], ''[[:s:Preface to the Poems Composed at the Orchid Pavilion|Preface to the Poems Composed at the Orchid Pavilion]]''" },
	['Laocan Youji']  =  { "WVC",  "'''1907''' " .. CE .. ", [[w:Liu E|Liu E]], ''[[w:The Travels of Lao Can|The Travels of Lao Can]]''" },
	['Liaozhai']  =  { "CL-L",  "'''1740''' " .. CE .. ", [[w:Pu Songling|Pu Songling]], ''[[:s:Strange Stories from a Chinese Studio|Strange Stories from a Chinese Studio]]''" },
    ['Lienvzhuan']   =  { "CL",  "The ''[[w:Biographies of Exemplary Women|Biographies of Exemplary Women]]'', 2<sup>nd</sup> century " .. BCE },
	['Liezi']        =  { "CL",  "''[[w:Liezi|Liezi]]'', 1<sup>st</sup> – 5<sup>th</sup> century " .. CE },
	['Liezi-C']      =  { "CL",  "''[[w:Liezi|Liezi]]'', 1<sup>st</sup> – 5<sup>th</sup> century " .. CE .. ", translated based on [[w:Thomas Cleary|Thomas Cleary]]'s version" },
	['Liezi-G']      =  { "CL",  "''[[w:Liezi|Liezi]]'', 1<sup>st</sup> – 5<sup>th</sup> century " .. CE .. ", translated based on [[w:A. C. Graham|A. C. Graham]]'s version" },
	['Liji']         =  { "CL",  "The ''[[w:Book of Rites|Book of Rites]]'', " .. circa .. " 4<sup>th</sup> – 2<sup>nd</sup> century " .. BCE },
	['Liji-L']       =  { "CL",  "The ''[[w:Book of Rites|Book of Rites]]'', " .. circa .. " 4<sup>th</sup> – 2<sup>nd</sup> century " .. BCE .. ", translated based on [[w:James Legge|James Legge]]'s version" },
	['Lingqijing']   =  { "CL",  "''[[w:Lingqijing|The Divine Chess Classic]]''" },
    ['Lingwai Daida']   =  { "CL",  "[[w:zh:周去非|Zhou Qufei]], ''[[w:Lingwai Daida|Representative Answers from the Region beyond the Mountains]]'', 12<sup>th</sup> century " .. CE },
	['Liutao']       =  { "CL",  "''[[w:Six Secret Teachings|Six Secret Teachings]]'', " .. circa .. " 475 – 221 " .. BCE },
	['Liutao-S']     =  { "CL",  "''[[w:Six Secret Teachings|Six Secret Teachings]]'', " .. circa .. " 475 – 221 " .. BCE .. ", translated based on Ralph D. Sawyer's version" },
	['Lunyu']        =  { "CL",  "The ''[[w:Analects|Analects]] of Confucius'', " .. circa .. " 475 – 221 " .. BCE },
	['Lvshi Chunqiu']=  { "CL",  "[[w:Lü Buwei|Lü Buwei]], ''[[w:Lüshi Chunqiu|Master Lü's Spring and Autumn Annals]]'', 239 " .. BCE },
	['Lunheng']      =  { "CL",  "[[w:Wang Chong|Wang Chong]], ''[[w:Lunheng|Lun Heng]]'' (''Discussive Weighing''), 80 " .. CE },
	['Lunheng-F']      =  { "CL",  "[[w:Wang Chong|Wang Chong]], ''[[w:Lunheng|Lun Heng]]'' (''Discussive Weighing''), 80 " .. CE .. ", translated based on Alfred Forke's version" },
	['Mencius']      =  { "CL",  "''[[w:Mencius (book)|Mencius]]'', " .. circa .. " 4<sup>th</sup> century " .. BCE },
	['Mencius-L']    =  { "CL",  "''[[w:Mencius (book)|Mencius]]'', " .. circa .. " 4<sup>th</sup> century " .. BCE .. ", translated based on [[w:James Legge|James Legge]]'s version" },
	['Mengxi Bitan']    =  { "CL-L", "'''1088''' " .. CE ..  ", [[w:Shen Kuo|Shen Kuo]], ''[[w:Dream Pool Essays|Dream Pool Essays]]''" },
	['Mengzi']       =  { "CL",  "''[[w:Mencius (book)|Mencius]]'', " .. circa .. " 4<sup>th</sup> century " .. BCE },
	['Mengzi-L']     =  { "CL",  "''[[w:Mencius (book)|Mencius]]'', " .. circa .. " 4<sup>th</sup> century " .. BCE .. ", translated based on [[w:James Legge|James Legge]]'s version" },
	['Mingshi']         =  { "CL-L",  "'''17<sup>th</sup>-18<sup>th</sup> century''', ''[[w:History of Ming|History of Ming]]''" },
	['Mozi']         =  { "CL",  "''[[w:Mozi (book)|Mozi]]'', " .. circa .. " 4<sup>th</sup> century " .. BCE },
	['Mozi-M']       =  { "CL",  "''[[w:Mozi (book)|Mozi]]'', " .. circa .. " 4<sup>th</sup> century " .. BCE .. ", translated based on [[w:zh:梅貽寶|Y. P. Mei]]'s version" },
    ['Mutianzizhuan']=  { "CL",  "The ''[[w:Tale of King Mu, Son of Heaven|Tale of King Mu, Son of Heaven]]'', " .. circa .. " 370 – 330 " .. BCE },
    ['Mutianzizhuan-E']=  { "CL",  "The ''[[w:Tale of King Mu, Son of Heaven|Tale of King Mu, Son of Heaven]]'', " .. circa .. " 370 – 330 " .. BCE .. ", translated based on [[w:Ernst Johann Eitel|E. J. Eitel]]'s version" },
    ['Mutianzizhuan-Z']=  { "CL",  "The ''[[w:Tale of King Mu, Son of Heaven|Tale of King Mu, Son of Heaven]]'', " .. circa .. " 370 – 330 " .. BCE .. ", translated based on Zheng Dekun's version" },
	['Nanqishu']     =  { "CL-L",  "The ''[[w:Book of Qi|Book of Southern Qi]]'', by [[w:Xiao Zixian|Xiao Zixian]], 6<sup>th</sup> century " .. CE },
	['Nanshi']       =  { "CL-L",  "'''659''' " .. CE .. ", [[w:Li Dashi|Li Dashi]] and Li Yanshou, ''[[w:History of the Southern Dynasties|History of the Southern Dynasties]]''" },
	['Paian Jingqi 1'] = { "WVC", "'''1628''' " .. CE .. ", [[w:Ling Mengchu|Ling Mengchu]], ''[[w:Slapping the Table in Amazement|Slapping the Table in Amazement]]'' I" },
	['Paian Jingqi 2'] = { "WVC", "'''1632''' " .. CE .. ", [[w:Ling Mengchu|Ling Mengchu]], ''[[w:Slapping the Table in Amazement|Slapping the Table in Amazement]]'' II" },
	['Peizhu']       =  { "CL-L",  "[[w:Pei Songzhi|Pei Songzhi]], ''[[w:Annotations to Records of the Three Kingdoms|Annotations to Records of the Three Kingdoms]]'', circa 5<sup>th</sup> century " .. CE },
	['Qianfu Lun']    =  { "CL",  "[[w:Wang Fu (Han dynasty)|Wang Fu]], ''[[w:Qianfu Lun|Comments of a Recluse]]'', " .. circa .. " 2<sup>nd</sup> century " .. CE },
	['Qianfu Lun-P']  =  { "CL",  "[[w:Wang Fu (Han dynasty)|Wang Fu]], ''[[w:Qianfu Lun|Comments of a Recluse]]'', " .. circa .. " 2<sup>nd</sup> century " .. CE .. ", translated based on Margaret Pearson's version" },
	['Qianjin Yaofang']  =  { "CL-L",  "[[w:Sun Simiao|Sun Simiao]], ''[[w:Beiji qianjin yaofang|Essential Formulas Worth a Thousand Weights in Gold to Prepare for Emergencies]]'', 652 " .. CE },
	['Qianziwen'] =  { "CL-L",  "Zhou Xingsi, ''[[w:Thousand Character Classic|Thousand Character Classic]]'', circa 6<sup>th</sup> century " .. CE  },
	['Qimin Yaoshu'] =  { "CL-L",  "'''544''' " .. CE .. ", Jia Sixie, ''[[w:Qimin Yaoshu|Qimin Yaoshu]]''" },
	['Qingshigao']   =  { "CL-L",  "'''1929''', [[w:Zhao Erxun|Zhao Erxun]] (lead editor), ''[[w:Draft History of Qing|Draft History of Qing]]''" },
	['Rulin Waishi'] =  { "WVC",  "[[w:Wu Jingzi|Wu Jingzi]], ''[[w:The Scholars (novel)|The Scholars]]'', 1750 " .. CE },
    ['Rulin Waishi-Y'] =  { "WVC",  "[[w:Wu Jingzi|Wu Jingzi]], ''[[w:The Scholars (novel)|The Scholars]]'', 1750 " .. CE .. ", translated based on [[w:Yang Xianyi|Yang Xianyi]] and [[w:Gladys Yang|Gladys Yang]]'s version" },
	['Sanlve']         =  { "CL",  "''[[w:Three Strategies of Huang Shigong|Three Strategies of Huang Shigong]]]'', 3<sup>th</sup> century " .. BCE .." – 1<sup>nd</sup> century " .. CE },
	['Sanlve-S']       =  { "CL",  "''[[w:Three Strategies of Huang Shigong|Three Strategies of Huang Shigong]]]'', 3<sup>th</sup> century " .. BCE .." – 1<sup>nd</sup> century " .. CE .. ", translated based on Ralph D. Sawyer's version" },
	['Sanguozhi']    =  { "CL-L",  "[[w:Chen Shou|Chen Shou]], ''[[w:Records of the Three Kingdoms|Records of the Three Kingdoms]]'', circa 3<sup>rd</sup> century " .. CE },
	['Sanguo Yanyi'] =  { "WVC",  "''[[w:Romance of the Three Kingdoms|Romance of the Three Kingdoms]]'', circa 14<sup>th</sup> century " .. CE },
	['Sanxia Wuyi']  =  { "WVC",  "''[[w:The Seven Heroes and Five Gallants|The Three Heroes and Five Gallants]]'', 1883 " .. CE },
	['Sanzijing']    =  { "CL-L",  "''[[w:Three Character Classic|Three Character Classic]]'', circa 13<sup>th</sup> century " .. CE },
	['Shangjunshu']  =  { "CL",  "The ''[[w:The Book of Lord Shang|Book of Lord Shang]]'', circa 3<sup>rd</sup> century " .. BCE },
	['Shangjunshu-D']  =  { "CL",  "The ''[[w:The Book of Lord Shang|Book of Lord Shang]]'', circa 3<sup>rd</sup> century " .. BCE .. ", translated based on [[w:J.J.L. Duyvendak|J.J.L. Duyvendak]]'s version" },
	['Shangshu']     =  { "CL",  "The ''[[w:Book of Documents|Book of Documents]]'', circa 4<sup>th</sup> – 3<sup>rd</sup> century " .. BCE },
	['Shangshu-K']   =  { "CL",  "The ''[[w:Book of Documents|Book of Documents]]'', circa 4<sup>th</sup> – 3<sup>rd</sup> century " .. BCE .. ", translated based on [[w:Bernhard Karlgren|Bernhard Karlgren]]'s version" },
	['Shangshu-L']   =  { "CL",  "The ''[[w:Book of Documents|Book of Documents]]'', circa 4<sup>th</sup> – 3<sup>rd</sup> century " .. BCE .. ", translated based on [[w:James Legge|James Legge]]'s version" },
	['Shanhaijing']  =  { "CL",  "The ''[[w:Classic of Mountains and Seas|Classic of Mountains and Seas]]''" },
	['Shanhaijing-B']  =  { "CL",  "The ''[[w:Classic of Mountains and Seas|Classic of Mountains and Seas]]'', translation from ''The Classic of Mountains and Seas'' (1999), by Anne Birrell" },
	['Shennong Ben Cao Jing']  =  { "CL",  "''[[w:Shennong Ben Cao Jing|The Divine Farmer's Materia Medica]]]'', 206 " .. BCE .." – 220 " .. CE },
	['Shennong Ben Cao Jing-Y']  =  { "CL",  "''[[w:Shennong Ben Cao Jing|The Divine Farmer's Materia Medica]]]'', 206 " .. BCE .." – 220 " .. CE .. ", translated based on Yang Shou-zhong's version" },
	['Shiji']        =  { "CL",  "The ''[[w:Records of the Grand Historian|Records of the Grand Historian]]'', by [[w:Sima Qian|Sima Qian]], " .. circa .. " 91 " .. BCE },
	['Shiji-A']      =  { "CL",  "The ''[[w:Records of the Grand Historian|Records of the Grand Historian]]'', by [[w:Sima Qian|Sima Qian]], " .. circa .. " 91 " .. BCE .. ", translated based on Herbert J. Allen's version" },
	['Shiji-W']      =  { "CL",  "The ''[[w:Records of the Grand Historian|Records of the Grand Historian]]'', by [[w:Sima Qian|Sima Qian]], " .. circa .. " 91 " .. BCE .. ", translated based on [[w:Burton Watson|Burton Watson]]'s version" },
	['Shijing']      =  { "CL-PC",  "The ''[[w:Classic of Poetry|Classic of Poetry]]'', " .. circa .. " 11<sup>th</sup> – 7<sup>th</sup> centuries " .. BCE .. ", translated based on [[w:James Legge|James Legge]]'s version" },
	['Shijing-K']      =  { "CL-PC",  "The ''[[w:Classic of Poetry|Classic of Poetry]]'', " .. circa .. " 11<sup>th</sup> – 7<sup>th</sup> centuries " .. BCE .. ", translated based on [[w:Bernhard Karlgren|Bernhard Karlgren]]'s version" },
	['Shijing-Xu']   =  { "CL",  "''Preface to Mao's Odes'' (Commentary on the ''[[w:Classic of Poetry|Classic of Poetry]]''), mid 2<sup>nd</sup> century " .. BCE  },
	['Shishuo Xinyu']=  { "CL-L",  "[[w:zh:劉義慶|Liu Yiqing]] (editor), ''[[w:A New Account of the Tales of the World|A New Account of the Tales of the World]]'', 5<sup>th</sup> century " .. CE },
	['Shitong']     =  { "CL-L",  "[[w:Liu Zhiji|Liu Zhiji]], ''[[w:Shitong|Shitong]]'', circa 708 – 710 " .. CE },
	['Shuihuzhuan']  =  { "WVC", "[[w:Shi Nai'an|Shi Nai'an]], ''[[w:Water Margin|Water Margin]]'', circa 14<sup>th</sup> century " .. CE },
	['Shuijingzhu']  =  { "CL-L", "[[w:Li Daoyuan|Li Daoyuan]], ''[[w:Commentary on the Water Classic|Commentary on the Water Classic]]'', 386-534 " .. CE },
	['Shujing']      =  { "CL",  "The ''[[w:Book of Documents|Book of Documents]]'', circa 7<sup>th</sup> – 4<sup>th</sup> centuries " .. BCE },
	['Shujing-L']    =  { "CL",  "The ''[[w:Book of Documents|Book of Documents]]'', circa 7<sup>th</sup> – 4<sup>th</sup> centuries " .. BCE .. ", translated based on [[w:James Legge|James Legge]]'s version" },
	['Shuowen']      =  { "CL",  "''[[w:Shuowen Jiezi|Shuowen Jiezi]]'', circa 2<sup>nd</sup> century " .. CE },
    ['Shuoyuan']     =  { "CL",  "''[[w:Shuoyuan|Shuoyuan]]'', circa 1<sup>st</sup> century " .. BCE },
	['Simafa']      =  { "CL",  "''[[w:The Methods of the Sima|The Methods of the Sima]]'', circa 4<sup>th</sup> century " .. BCE },
	['Simafa-S']    =  { "CL",  "''[[w:The Methods of the Sima|The Methods of the Sima]]'', circa 4<sup>th</sup> century " .. BCE .. ", translated based on Ralph D. Sawyer's version" },
	['Songshi']      =  { "CL-L",  "'''1345''' " .. CE .. ", [[w:Toqto'a (Yuan dynasty)|Toqto'a]] (lead editor), ''[[w:History of Song (book)|History of Song]]''" },
    ['Songshu']      =  { "CL-L",  "[[w:Shen Yue|Shen Yue]], ''[[w:Book of Song|Book of Song]]'', 492-493 " .. CE},
    ['Soushenji']    =  { "CL",  "''[[w:Soushen Ji|In Search of the Sacred]]'', circa 3<sup>rd</sup> century " .. CE },
    ['Suishu']       =  { "CL-L",  "The ''[[w:Book of Sui|Book of Sui]]'', 636 " .. CE },
	['Sunzi']        =  { "CL",  "''[[w:The Art of War|The Art of War]]'', circa 5<sup>th</sup> century " .. BCE },
	['Sunzi-G']      =  { "CL",  "''[[w:The Art of War|The Art of War]]'', circa 5<sup>th</sup> century " .. BCE .. ", translated based on [[w:Lionel Giles|Lionel Giles]]'s version" },
	['Sunzi-S']      =  { "CL",  "''[[w:The Art of War|The Art of War]]'', circa 5<sup>th</sup> century " .. BCE .. ", translated based on Ralph D. Sawyer's version" },
	['Taiping Guangji']={ "CL-L",  "''[[w:Taiping Guangji|Taiping Guangji]]'' (''Extensive Records of the Taiping Era''), 978 " .. CE },
	['Taiping Yulan']=  { "CL-L",	 "''[[w:Taiping Yulan|Taiping Yulan]]'' (''Readings of the Taiping Era''), 977 – 983 " .. CE },
	['Taixuanjing']  =  { "CL",  "[[w:Yang Xiong (author)|Yang Xiong]], ''[[w:Taixuanjing|The Canon of Supreme Mystery]]'', 2 " .. BCE },
	['Tingxun Geyan']=  { "CL", "[[w:Kangxi Emperor|Qing Emperor Kangxi]], ''Guidelines for Families''" },
	['Tongdian']     =  { "CL-L",	 "[[w:Du You|Du You]], ''[[w:Tongdian|Tongdian]]'', 766 – 801 " .. CE },
	['UM']           =  { "MSC", "[http://nlp2ct.cis.umac.mo/um-corpus/ UM-Corpus: A Large English-Chinese Parallel Corpus] by NLP2CT" },
	['Weiliaozi']       =  { "CL",  "''[[w:Wei Liaozi|Wei Liaozi]]'', " .. circa .. " 4<sup>th</sup> – 3<sup>rd</sup> centuries " .. BCE },
	['Weiliaozi-S']     =  { "CL",  "''[[w:Wei Liaozi|Wei Liaozi]]'', " .. circa .. " 4<sup>th</sup> – 3<sup>rd</sup> centuries " .. BCE .. ", translated based on Ralph D. Sawyer's version" },
    ['Weilve']       =  { "CL",  "[[w:Yu Huan|Yu Huan]], ''[[w:Weilüe|Weilüe]]'', 239  – 265 " .. CE },
	['Weishu']       =  { "CL-L",  "[[w:Wei Shou|Wei Shou]], ''[[w:Book of Wei|Book of Wei]]'', 551 – 554 " .. CE },
	['Wenxin Diaolong'] =  { "CL",  "[[w:Liu Xie|Liu Xie]], ''[[w:The Literary Mind and the Carving of Dragons|The Literary Mind and the Carving of Dragons]]'', " .. circa .. " 5<sup>th</sup> century " .. CE  },
	['Wenzi']        =  { "CL",  "''[[w:Wenzi|Wenzi]]''" },
	['WGWSS']        =  { "CL",  "Forged Old Text of the ''[[w:Book of Documents|Book of Documents]]'', circa 3<sup>rd</sup> – 4<sup>th</sup> century " .. CE },
	['Wuzi']         =  { "CL",  "''[[w:Wuzi|Wuzi]]]'', 5<sup>th</sup> – 4<sup>th</sup> century " .. BCE },
	['Wuzi-S']       =  { "CL",  "''[[w:Wuzi|Wuzi]]]'', 5<sup>th</sup> – 4<sup>th</sup> century " .. BCE .. ", translated based on Ralph D. Sawyer's version" },
    ['Xiaojing']     =  { "CL",  "''[[w:Classic of Filial Piety|Classic of Filial Piety]]'',  circa 475 – 221 " .. BCE },
	['Xingshi Hengyan']={ "WVC", "[[w:Feng Menglong|Feng Menglong]], ''[[w:Stories to Awaken the World|Stories to Awaken the World]]'', 1627 " .. CE },
	['Xingshi Yinyuan Zhuan']={ "WVC", "Xizhou Sheng, ''[[w:Xingshi Yinyuan Zhuan|Marriage Destinies to Awaken the World]]'', 17<sup>th</sup> century " .. CE },
	['Xishuangji']   =  { "WVC", "[[w:Wang Shifu|Wang Shifu]], ''[[w:The Story of the Western Wing|The Story of the Western Wing]]'', 13<sup>th</sup> – 14<sup>th</sup> centuries " .. CE },
	['Xiyouji']      =  { "WVC", "[[w:Wu Cheng'en|Wu Cheng'en]], ''[[w:Journey to the West|Journey to the West]]'', 16<sup>th</sup> century " .. CE },
	['Xiyouji-Y']    =  { "WVC", "[[w:Wu Cheng'en|Wu Cheng'en]], ''[[w:Journey to the West|Journey to the West]]'', 16<sup>th</sup> century " .. CE .. ", translation from ''The Journey to the West'' (2012), by [[w:Anthony C. Yu|Anthony C. Yu]]" },
	['Xintangshu']   =  { "CL-L",  "The ''[[w:New Book of Tang|New Book of Tang]]'', 1060 " .. CE },
	['Xinyu']        =  { "CL",  "[[w:Lu Jia (Western Han)|Lu Jia]], ''[[w:zh:新語 (中國古籍)|Xinyu]]'' (''A New Discourse''), " .. circa .. " 197 " .. BCE },
	['Xunzi']        =  { "CL",  "''[[w:Xunzi (book)|Xunzi]]'', " .. circa .. " 3<sup>rd</sup> century " .. BCE },
	['Yantielun']    =  { "CL",  "[[w:zh:桓寬|Huan Kuan]], ''[[w:Discourses on Salt and Iron|Discourses on Salt and Iron]]'', " .. circa .. " 1<sup>st</sup> century " .. BCE },
	['Yanshi Jiaxun']=  { "CL-L",  "[[w:Yan Zhitui|Yan Zhitui]], ''The Family Instructions of Master Yan'', 6<sup>th</sup> century " .. CE },
	['Yanzi Chunqiu']=  { "CL",  "''[[w:Yanzi Chunqiu|Annals of Master Yan]]'', " .. circa .. " 3<sup>rd</sup> century " .. BCE },
	['Yijing']       =  { "CL-PC",  "''[[w:I Ching|I Ching]]'', 11<sup>th</sup> – 8<sup>th</sup> century " .. BCE },
	['Yijing-L']     =  { "CL-PC",  "''[[w:I Ching|I Ching]]'', 11<sup>th</sup> – 8<sup>th</sup> century " .. BCE .. ", translated based on [[w:James Legge|James Legge]]'s version" },
    ['Yili']         =  { "CL",  "''[[w:Yili|Etiquette and Ceremonial]]'', circa 475 – 221 " .. BCE },
    ['Yili-S']       =  { "CL",  "''[[w:Yili|Etiquette and Ceremonial]]'', circa 475 – 221 " .. BCE .. ", translated based on John Steele's version" },
	['Yilin']        =  { "CL",  "[[w:zh:焦贛|Jiao Gong]], ''[[w:Jiaoshi Yilin|Yilin]]'', 1<sup>st</sup> century " .. BCE },
	['Yiwen Leiju']    =  { "CL-L",  "''[[w:Yiwen Leiju|Yiwen Leiju]]'', 624 " .. CE },
	['Yizhoushu']    =  { "CL",  "''[[w:Yi Zhou Shu|Lost Book of Zhou]]'', circa 4<sup>th</sup> – 1<sup>st</sup> centuries " .. BCE },
	['Yuandianzhang']=  { "CL-L",  "''[[w:zh:元典章|Statutes of the Yuan dynasty]]'', 1322–1323 " .. CE },
	['Zhanguoce']    =  { "CL",  "''[[w:Zhan Guo Ce|Zhanguo Ce]]'', circa 5<sup>th</sup> – 3<sup>rd</sup> centuries " .. BCE },
	['Zhanguoce-C']    =  { "CL",  "''[[w:Zhan Guo Ce|Zhanguo Ce]]'', circa 5<sup>th</sup> – 3<sup>rd</sup> centuries " .. BCE .. ", translated based on J. I. Crump's version" },
	["Zhaoshi Gu'er"]=  { "WVC",  "'''Yuan Dynasty''', [[w:zh:紀君祥|Ji Junxiang]], ''[[w:The Orphan of Zhao|The Orphan of Zhao]]''" },
	['Zhouli']       =  { "CL",  "''[[w:Rites of Zhou|Rites of Zhou]]'', circa 3<sup>rd</sup> century " .. BCE },
	['Zhoushu']       =  { "CL-L",  "'''636''' " .. CE .. ", [[w:Linghu Defen|Linghu Defen]], ''[[w:Book of Zhou|Book of Zhou]]''" },
	['Zhuangzi']     =  { "CL",  "''[[w:Zhuangzi (book)|Zhuangzi]]'', circa 3<sup>rd</sup> – 2<sup>nd</sup> centuries " .. BCE },
	['Zhuangzi-L']   =  { "CL",  "''[[w:Zhuangzi (book)|Zhuangzi]]'', circa 3<sup>rd</sup> – 2<sup>nd</sup> centuries " .. BCE .. ", translated based on [[w:James Legge|James Legge]]'s version" },
	['Zhuangzi-W']   =  { "CL",  "''[[w:Zhuangzi (book)|Zhuangzi]]'', circa 3<sup>rd</sup> – 2<sup>nd</sup> centuries " .. BCE .. ", translation from ''The Complete Works Of Chuang Tzu'' (2013), by [[w:Burton Watson|Burton Watson]]" },
    ['Zhushu Jinian'] =  { "CL",  "''[[w:Bamboo Annals|Bamboo Annals]]'',  circa 475 – 221 " .. BCE },
	['Zhuzi Jiaxun'] =  { "CL-L",  "[[w:zh:朱用純|Zhu Yongchun]], ''[[w:zh:朱柏廬治家格言|Zhu Zi's Family Maxims]]'', 17<sup>th</sup> century " .. CE },
	['Zhuzi Yulei'] = {"WVC", "Various editors, ''[[w:Zhuzi yulei|Collected Conversations of Master Zhu]]'', " .. circa .. " 13<sup>th</sup> century " .. CE},
	['Zibuyu']       =  { "CL-L",  "[[w:Yuan Mei|Yuan Mei]], ''[[w:What the Master Would Not Discuss|What the Master Would Not Discuss]]'', 1788 " .. CE },
	['Zizhi Tongjian']       =  { "CL-L",  "'''1084''' " .. CE .. ", [[w:Sima Guang|Sima Guang]], ''[[w:Comprehensive Mirror to Aid in Government|Comprehensive Mirror to Aid in Government]]''" },
	['Zuozhuan']     =  { "CL",  "''[[w:Zuo zhuan|Commentary of Zuo]]'', " .. circa .. " 4<sup>th</sup> century " .. BCE },
	['Zuozhuan-D']   =  { "CL",  "''[[w:Zuo zhuan|Commentary of Zuo]]'', " .. circa .. " 4<sup>th</sup> century " .. BCE .. ", translation from ''Zuozhuan: Commentary on the \"Spring and Autumn Annals\"'' (2017), by Stephen Durrant, Wai-yee Li and David Schaberg" },
	['Zuozhuan-L']   =  { "CL",  "''[[w:Zuo zhuan|Commentary of Zuo]]'', " .. circa .. " 4<sup>th</sup> century " .. BCE .. ", translated based on [[w:James Legge|James Legge]]'s version" },
	
	['Mao25']      =  format_mao("1925", "中國社會各階級的分析", "Analysis of the Classes in Chinese Society", "1", "1"),
	['Mao27']      =  format_mao("1927", "[[w:zh:湖南农民运动考察报告|湖南農民運動考察報告]]", "[[w:Report on an Investigation of the Peasant Movement in Hunan|Report on an Investigation of the Peasant Movement in Hunan]]", "1", "2"),
	['Mao35']      =  format_mao("1935", "論反對日本帝國主義的策略", "On Tactics Against Japanese Imperialism", "1", "11"),
	['Mao36']      =  format_mao("1936", "中國革命戰爭的戰略問題", "Problems of Strategy in China's Revolutionary War", "1", "12"),
	['MaoSJL']     =  format_mao("1937", "[[w:zh:實踐論|實踐論]]", "[[w:On Practice|On Practice]]", "1", "16"),
	['MaoMDL']     =  format_mao("1937", "[[w:zh:矛盾論|矛盾論]]", "[[w:On Contradiction|On Contradiction]]", "1", "17"),
	['MaoZYZY']    =  format_mao("1937", "反對自由主義", "Combat Liberalism", "2", "03"),
	['Mao38']      =  format_mao("1938", "[[w:zh:論持久戰|論持久戰]]", "[[w:On Protracted War|On Protracted War]]", "2", "09"),
	['MaoZGGM']    =  format_mao("1939", "中國革命和中國共產黨", "The Chinese Revolution and the Chinese Communist Party", "2", "23"),
	['MaoXMZZY']   =  format_mao("1940", "[[w:zh:新民主主義論|新民主主義論]]", "On New Democracy", "2", "26"),
	['MaoRectify'] =  format_mao("1942", "整頓黨的作風", "Rectify the Party's Style of Work", "3", "06"),
	['MaoYanan']   =  format_mao("1942", "[[w:zh:在延安文藝座談會上的講話|在延安文藝座談會上的講話]]", "[[w:Yan'an Forum|Talks at the Yenan Forum on Literature and Art]]", "3", "08"),
	['Mao45']      =  format_mao("1945", "[[s:zh:論聯合政府|論聯合政府]]", "On Coalition Government", "3", "25"),
	['Mao56']      =  format_mao("1956", "[[w:zh:論十大關係|論十大關係]]", "[[w:Ten Major Relationships|On the Ten Major Relationships]]", "5", "51"),
	['Mao57']      =  format_mao("1957", "關於正確處理人民內部矛盾的問題", "On the Correct Handling of Contradictions Among the People", "5", "58"),
}

data.pron_correction = {
	["cmn"] = {},
	["yue"] = {
		["錢"] = "cin4",
		["道"] = "dou6",
		["稱"] = "cing1",
		["噏"] = "ngap1",
	},
	["hak"] = {
		["阿"] = "-â-",
		["媸"] = "-ché-", ["獎"] = "-chióng-", ["竹"] = "-chuk-",
		["茶"] = "chhà", ["蚻"] = "-chha̍t-", ["曾"] = "-chhèn-", ["千"] = "-chhiên-", ["竄"] = "-chhon-", ["捽"] = "-chhu̍t-",
		["仔"] = "-é-", ["𫣆"] = "-ên-",
		["客"] = "-hak-",
		["機"] = "-kî-", ["𥘹"] = "-kì-", ["溝"] = "-kiêu-", ["稿"] = "-kó-",
		["罅"] = "-la-", ["壢"] = "-lak-", ["摎"] = "-lâu-", ["㧯"] = "-lâu-", ["恅"] = "-láu-", ["俚"] = "-lî-", ["羅"] = "-lò-", ["擂"] = "-lùi-",
		["閩"] = "-mén-", ["美"] = "-mî-", ["忘"] = "-mong-", ["蚊"] = "-mûn-",
		["腦"] = "-nó-", ["濃"] = "-nùng-",
		["𠊎"] = "-ngài-", ["祢"] = "-ngì-",
		["孲"] = "-ò-", ["𡟓"] = "-ôi-",
		["錶"] = "-péu-", ["輩"] = "-pi-", ["𡜵"] = "-pû-",
		["婆"] = "-phò-",
		["使"] = "-sṳ́-", ["史"] = "-sṳ́-", ["視"] = "sṳ", ["脣"] = "-sùn-",
		["點"] = "-tiám-",
		["𢯭"] = "-then-", ["電"] = "-thien-", ["唐"] = "-thòng-", ["筒"] = "-thùng",
		["裕"] = "-yi-",
	},
	["nan-hbl"] = {
		["阿"] = "-a-", ["仔"] = "-á-", ["矣"] = "-ah-", ["啊"] = "-ah-",
		["䆀"] = "-bái-", ["袂"] = "-bē-", ["欲"] = "-beh-", ["覕"] = "-bih-", ["盟"] = "-bêng-", ["務"] = "-bū-",
		["欉"] = "-châng-", ["十"] = "-cha̍p-", ["誌"] = "-chì-", ["遮"] = "-chiah-", ["針"] = "-chiam-", ["窒"] = "-chit-", ["鯽"] = "-chit-", ["一"] = "-chi̍t-", ["睭"] = "-chiu-", ["慈"] = "-chû-", ["𠞩"] = "-chûi-",
		["𨑨"] = "-chhit-", ["𤆬"] = "-chhōa-", ["攢"] = "-chhoân-",
		["的"] = "-ê-", ["个"] = "-ê-", ["憶"] = "-ek-",
		["𠢕"] = "-gâu-", ["偌"] = "-gōa-", ["囡"] = "-gín-",
		["耳"] = "-hīⁿ-", ["予"] = "-hō͘-",
		["已"] = "-í-", ["也"] = "-iā-", ["𪜶"] = "-in-",
		["字"] = "-jī-", ["然"] = "-jiân-", ["日"] = "-ji̍t-",
		["共"] = "-kā-", ["佮"] = "-kah-", ["甲"] = "-kah-", ["矸"] = "-kan-", ["到"] = "-kàu-", ["竟"] = "kèng", ["行"] = "-kiâⁿ-", ["勼"] = "-kiu-", ["閣"] = "-koh-", ["擱"] = "-koh-", ["講"] = "-kóng-",
		["跤"] = "-kha-", ["較"] = "-khah-", ["徛"] = "-khiā-", ["課"] = "-khò",
		["人"] = "-lâng-", ["汝"] = "-lí-", ["旅"] = "-lí-", ["啉"] = "-lim-", ["暖"] = "-loán-", ["戀"] = "-loân-", ["攏"] = "-lóng-",
		["毋"] = "-m̄-", ["嬤"] = "-má-",
		["喔"] = "-o͘h-",
		["爸"] = "-pē-", ["悲"] = "-pi-",
		["麭"] = "-pháng-",
		["三"] = "-saⁿ-", ["捨"] = "-siá-", ["閃"] = "-siám-", ["雙"] = "-siang-", ["啥"] = "-siáⁿ-", ["心"] = "-sim-", ["俗"] = "-sio̍k-", ["傷"] = "-siong-", ["商"] = "-siong-", ["受"] = "-siū-", ["煞"] = "-soah-", ["士"] = "-sū-", ["雖"] = "-sui-", ["媠"] = "-súi-", ["遂"] = "-sūi-",
		["臺"] = "-tâi-", ["塊"] = "-tè-", ["咧"] = "-teh-", ["豬"] = "-ti-", ["戴"] = "-tì-", ["佇"] = "-tī-", ["典"] = "-tián-", ["躊"] = "-tiû-", ["斷"] = "-tn̄g-", ["多"] = "-to-", ["倒"] = "tó", ["拄"] = "-tú-", ["盹"] = "-tuh-", ["脣"] = "-tûn-",
		["太"] = "-thài-", ["刣"] = "-thâi-", ["讀"] = "-tha̍k-", ["窗"] = "-thang-", ["迌"] = "-thô-",
		["揻"] = "-ui-",
	},
	["wuu"] = {},
}

data.polysyllable_pron_correction = {
	["cmn"] = {
		["覺得"] = "juéde",
		["個中"] = "gèzhōng", ["個人"] = "gèrén", ["個個"] = "gègè", ["個兒"] = "gèr", ["個別"] = "gèbié", ["個子"] = "gèzi", ["個展"] = "gèzhǎn", ["個性"] = "gèxìng", ["個數"] = "gèshù", ["個案"] = "gè'àn",["個頭"] = "gètóu",  ["個體"] = "gètǐ"
	},
	["yue"] = {
		["屋企"] = "uk1 kei2", ["返屋企"] = "faan1 uk1 kei2",
		["知道"] = "zi1 dou3"
	},
	["hak"] = {
		["老鼠"] = "-lo-chhú-",
		["敗勢"] = "-phài-se-",
		["癩𰣻"] = "-thái-kô-",
		["台灣"] = "-Thòi-vàn-",
		["臺灣"] = "-Thòi-vàn-"
	},
	["nan-hbl"] = {
		["愛人"] = "-ài-jîn-",
		["饅頭"] = "-bán-thô-", ["門徒"] = "-bûn-tô͘-",
		["情批"] = "-chêng-phoe-", ["遮爾"] = "-chiah-nī-", ["這馬"] = "-chit-má-", ["作用"] = "-chok-iōng-",
		["請假"] = "-chhéng-ká-", ["親像"] = "-chhin-chhiūⁿ-",
		["偌爾"] = "-gōa-nī-",
		["一切"] = "-it-chhè-", ["一般"] = "-it-poaⁿ-", ["一直"] = "-it-ti̍t-",
		["人海"] = "-jîn-hái-", ["人生"] = "-jîn-seng-",
		["卡拉OK"] = "-kha-lá-ó͘-khe-",
		["旅行"] = "-lí-hêng-",
		["歐巴桑"] = "-o͘-bá-sáng-",
		["歹勢"] = "-pháiⁿ-sè-",
		["山珍海味"] = "-san-tin-hái-bī-", ["漩渦"] = "-soân-o-",
		["臺灣"] = "-Tâi-oân-", ["第一"] = "-tē-it-", ["的確"] = "-tek-khak-",
		["癩𰣻"] = "-thái-ko-",
	},
	["wuu"] = {},
}

return data
